# Werkcollege-opdrachten Week 1.1

## Maak een virtual environment

Zorg dat je met behulp van de handleiding *Bouw en gebruik van virtual environments - Handleiding* een virtual environment hebt gemaakt, dat jou en je duopartner garandeert altijd dezelfde versie van geïmporteerde dependencies te gebruiken.<br>
Voeg hier vervolgens de pandas- en de sqlite3-dependency aan toe.<br>
Als je dit allemaal goed hebt gedaan moet de onderstaande code bij jullie allebei succesvol runnen:

In [1]:
import pandas as pd
import sqlite3
import warnings
warnings.simplefilter('ignore')

N.B.: de 2 reeds geschreven coderegels zorgen ervoor dat eventuele warnings, die code-outputs lelijker maken, uitgezet worden.

Zorg er daarnaast voor dat je...
- Het bestand Waarheidstabel.png in dezelfde map als dit notebook hebt staan.
- Het bestand Prinstabel.png in dezelfde map als dit notebook hebt staan.
- Alle informatie onder het kopje *Basisoperaties* van de cheatsheet *Van Java naar Python - Cheatsheet* bij de hand hebt.

## Output, variabelen en input

Geef code waarmee het volgende op het scherm komt te staan:<br>
geef me je geld <br>
of ik gebruik geweld, <br>
toen kwam de controle aangesneld

In [2]:
print("geef me je geld")
print("of ik gebruik geweld")
print("toen kwam de controle aangesneld")

geef me je geld
of ik gebruik geweld
toen kwam de controle aangesneld

Declareer 2 variabelen zodat de volgende tekst geprint wordt:<br>
Apenhoofd<br>
Paardenstaart

In [5]:
woord1 = "Apenhoofd"
woord2 = "Paardenstaart"

print(woord1)
print(woord2)

Apenhoofd
Paardenstaart

Voeg code toe zodat het programma het volgende doet:<br>
1): Op het scherm komt A, B, C, D, ..., F, G te staan<br>
2): De gebruiker voert een letter in<br>
3): Op het scherm komt te staan:<br>
Het is inderdaad:<br>
*ingevoerde letter*

In [12]:


print("A, B, C, D, ..., F, G")
letter = input()
print("Het is inderdaad:")
print(letter)

A, B, C, D, ..., F, G
Het is inderdaad:
E

## Stringconcatenatie en Rekenen

Schrijf code dat een inkomen inleest en het volgende uitprint:<br>
Uw inkomen (*ingelezen inkomen*) is zeer acceptabel.

In [15]:
inkomen = input()
print("Uw inkomen " + inkomen + " is zeer acceptabel.")

Uw inkomen kaas is zeer acceptabel.

De oppervlakte van een driehoek is 1/2 * hoogte * basis<br>
Schrijf code zodat het programma het volgende doet:<br>
1): Op het scherm komt Wat is de basis? te staan<br>
2): De gebruiker voert een basis in<br>
3): Op het scherm komt Wat is de hoogte? te staan<br>
4): De gebruiker voert een hoogte in<br>
5): Op het scherm komt: De oppervlakte van de driehoek is *berekende oppervlakte* te staan

In [19]:
basis = input("Wat is de basis? ")
hoogte = input("Wat is de hoogte? ")
oppervlakte = 0.5 * float(basis) * float(hoogte)
print("De oppervlakte van de driehoek is:", oppervlakte)

De oppervlakte van de driehoek is: 4.305

## if() en booleans

Schrijf code dat het volgende doet:<br>
1): De gebruiker voert in hoe oud iemand is<br>
2): De gebruiker voert in of de ouders meegekomen zijn (input is J of N)<br><br>

Als...
- Jonger dan 6, wel ouders: op het scherm staat Je mag het zwembad in
- Jonger dan 6, geen ouders: op het scherm staat Je mag het niet zwembad in
- Leeftijd vanaf 6, geen ouders: op het scherm staat Je mag het zwembad in als je een diploma hebt
- Leeftijd vanaf 6, wel ouders: op het scherm staat Waarom neem je nog je ouders mee?

In [2]:
leeftijd = int(input("Hoe oud ben je? "))
ouders = input("Zijn je ouders mee? (J/N) ")

if leeftijd < 6:
    if ouders == "J":
        print("Je mag het zwembad in")
    else:
        print("Je mag het niet zwembad in")

if leeftijd >= 6:
    if ouders == "N":
        print("Je mag het zwembad in als je een diploma hebt")
    else:
        print("Waarom neem je nog je ouders mee?")

Waarom neem je nog je ouders mee?

Schrijf code zodat de boolean-variabelen een en twee aangemaakt worden en waarmee de juiste waarde in de boolean-variabele uitkomst komt te staan. In de waarheidstabel hieronder staat wat de waarde van uitkomst is bij de verschillende mogelijke combinaties van een en twee.<br><br>
<img src="Waarheidstabel.png">

In [23]:
een = True
twee = False

uitkomst = not (een and not twee)

print(f"De waarde van uitkomst is: {uitkomst}")

De waarde van uitkomst is: False

## Functies

Schrijf een methode wachtwoord die als parameters twee woorden meekrijgt en het volgende controleert:
- Als de woorden gelijk zijn, print het programma gelijk.
- Als de woorden ongelijk zijn print het programma ongelijk.

Vergeet niet dat je de methode niet alleen aan moet maken, maar ook aan moet roepen om output te krijgen.

In [2]:
def wachtwoord(woord1, woord2):

    if (woord1 == woord2):
        print("gelijk")
    else: 
        print("ongelijk")


wachtwoord("wcbril", "wcbril")      
wachtwoord("wc", "aap")

gelijk
ongelijk

Schrijf de methode zoekPrins die als parameter een prinses meekrijgt en vervolgens de bijbehorende prins oplevert, volgens de volgende tabel:<br><br>
<img src="Prinstabel.png"><br>
Als de naam van de prinses niet in de tabel staat wordt het volgende door de methode teruggegeven: naamloos.<br>
Roep ten slotte de gemaakte methode ook daadwerkelijk aan met een zelfgekozen prinsessennaam.

In [25]:
def zoekPrins(prinses):
    
    koppels = {
        "Aurora": "Philip",
        "Ariël": "Eric",
        "Jasmine": "Aladdin",
        "Pocahontas": "John",
        "Belle": "Beast",
        "Tiana": "Naveen",
        "Mulan": "Shang"
    }
    
    if prinses in koppels:
        return koppels[prinses]
    else:
        return "naamloos"

print(zoekPrins("Tiana"))

Naveen

## While-loop

Schrijf de inhoud van de methode wachtwoord. Deze heeft geen parameters en laat de gebruiker twee wachtwoorden invoeren, waarna hij bekijkt of deze gelijk zijn. Zolang dat niet het geval is wordt er eerst Fout, probeer het opnieuw! uitgeprint en moet de gebruiker het opnieuw proberen.<br>Als de gebruiker het goed doet, komt er Succes! op het scherm te staan.

In [26]:
def wachtwoord():
    w1 = input("Voer wachtwoord 1 in: ")
    w2 = input("Voer wachtwoord 2 in: ")
    
    while w1 != w2:
        print("Fout, probeer het opnieuw!")
        w1 = input("Voer wachtwoord 1 in: ")
        w2 = input("Voer wachtwoord 2 in: ")
    
    print("Succes!")

wachtwoord()

Succes!

Schrijf de inhoud van de methode tafels. De methode print alle tafels vanaf 1 (dus inclusief de tafel van 1) tot en met de tafel van het meegekregen getal (dus inclusief de tafel van getal).  Zet een witregel tussen alle tafels in. <br>
Let op:
- Gebruik een while-loop
- Gebruik de reeds geschreven methode tafel om een tafel uit te printen

In [5]:
def tafels(getal: int):
    teller: int = 1

    while(teller <= 10):
        print(f'{teller} x {getal} = {teller * getal}')
        print("")
        teller += 1

x: int = int(input())
tafels(x)

1 x 7 = 7

2 x 7 = 14

3 x 7 = 21

4 x 7 = 28

5 x 7 = 35

6 x 7 = 42

7 x 7 = 49

8 x 7 = 56

9 x 7 = 63

10 x 7 = 70

## For-loop

Vervang de while-loop door een werkende for-loop. De uitkomst van het programma mag daarbij niet veranderen.

In [9]:
def loopje():

    aantal = 0

    for aantal in range(0 ,11):
        print(f"huidige getal: {aantal}")
        aantal += 1

loopje()

huidige getal: 0
huidige getal: 1
huidige getal: 2
huidige getal: 3
huidige getal: 4
huidige getal: 5
huidige getal: 6
huidige getal: 7
huidige getal: 8
huidige getal: 9
huidige getal: 10

Schrijf de methode checkEven die achtereenvolgens 12 getallen inleest en afdrukt hoe vaak het ingevoerde getal even was.

In [15]:
def checkEven():
    aantal_even = 0  
    teller = 0       
    
    while teller < 12:
        
        getal = int(input("Voer een getal in: "))
        
        
        if getal % 2 == 0:
            aantal_even += 1  
            
        teller += 1 
        
    print(aantal_even)


checkEven()

12

## Objectoriëntatie

Maak een minisysteem voor een kledingwinkel. Maak verschillende klassen voor verschillende soorten kledingstukken, waarbij sommige klassen geërfd worden van andere klassen.
- Maak een klasse Kledingstuk aan, waarin door de constructor een merk, een maat en een prijs geïnitialiseerd worden.
- Maak een klasse Broek en een klasse Shirt, beide erven van de klasse Kledingstuk. Voeg aan Broek een broek_type, en aan Shirt een shirt_type toe (d.m.v. constructorgebruik).
- Maak een klasse Spijkerbroek die erft van broek en een klasse Poloshirt die erft van shirt. Voeg aan Spijkerbroek een blauwtint toe, en aan Poloshirt een kraagsoort (d.m.v. constructorgebruik).
- Implementeer in elke klasse een beschrijvingmethode, waarmee alle informatie over het betreffende kledingstuk wordt afgedrukt.
- Maak van elke klasse een object aan en roep de beschrijvingmethode aan. Controleer nauwkeurig of alles naar behoren werkt.

In [3]:
class Kledingstuk:
    def __init__(self, merk, maat, prijs):
        self.merk = merk
        self.maat = maat
        self.prijs = prijs

    def beschrijving(self):
        print(f"Merk: {self.merk}, Maat: {self.maat}, Prijs: {self.prijs}")

class Broek(Kledingstuk):
    def __init__(self, merk, maat, prijs, broek_type):
        super().__init__(merk, maat, prijs)
        self.broek_type = broek_type

    def beschrijving(self):
        super().beschrijving()
        print(f"Type broek: {self.broek_type}")

class Shirt(Kledingstuk):
    def __init__(self, merk, maat, prijs, shirt_type):
        super().__init__(merk, maat, prijs)
        self.shirt_type = shirt_type

    def beschrijving(self):
        super().beschrijving()
        print(f"Type shirt: {self.shirt_type}")

class Spijkerbroek(Broek):
    def __init__(self, merk, maat, prijs, broek_type, blauwtint):
        super().__init__(merk, maat, prijs, broek_type)
        self.blauwtint = blauwtint

    def beschrijving(self):
        super().beschrijving()
        print(f"Blauwtint: {self.blauwtint}")

class Poloshirt(Shirt):
    def __init__(self, merk, maat, prijs, shirt_type, kraagsoort):
        super().__init__(merk, maat, prijs, shirt_type)
        self.kraagsoort = kraagsoort

    def beschrijving(self):
        super().beschrijving()
        print(f"Kraagsoort: {self.kraagsoort}")

sjinkie = Spijkerbroek("Levi's", 32, 89.99, "Slim", "Blauw")
polo = Poloshirt("Lacoste", "L", 75.00, "Katoen", "Klassiek")

print("--- Beschrijving Spijkerbroek ---")
sjinkie.beschrijving()
print("\n--- Beschrijving Poloshirt ---")
polo.beschrijving()

--- Beschrijving Spijkerbroek ---
Merk: Levi's, Maat: 32, Prijs: 89.99
Type broek: Slim
Blauwtint: Blauw

--- Beschrijving Poloshirt ---
Merk: Lacoste, Maat: L, Prijs: 75.0
Type shirt: Katoen
Kraagsoort: Klassiek

## Verzamelingen

Kijk nu naar alle info onder het kopje *Verzamelingen* van de cheatsheet *Van Java naar Python - Cheatsheet*.

Initialiseer een lijst met de naam mijn_lijst met de volgende waarden:<br>
Jelle, Marleen, Henk, Fatima, Jelle, Henk

In [5]:
mijn_lijst = ["Jelle", "Marleen", "Henk", "Fatima", "Jelle", "Henk"]

Probeer nu de eerste waarde uit te lijst te veranderen in een naam naar keuze. Lukt dat?

In [6]:
mijn_lijst[0] = "Raymond"

Maak van bovengenoemde lijst nu een tupel, genaamd: mijn_tupel.

In [4]:
mijn_tupel = ["Jelle", "Marleen", "Henk", "Fatima", "Jelle", "Henk"]

Probeer nu de laatste waarde uit te tupel te veranderen in een naam naar keuze. Lukt dat?

In [3]:
mijn_tupel[5] = "Raymond"

NameError: name 'mijn_tupel' is not defined

Initialiseer een dictionary met de volgende key-value-combinaties:
- naam: "Jelle"
- leeftijd: 30
- beroep: "Docent"
- hobby: "Volleybal"

In [5]:
mijn_dict = {
    "naam" : "Jelle",
    "leeftijd" : "30", 
    "beroep" : "Docent",
    "hobby" : "Volleybal"
}

Probeer nu de naam te veranderen naar een naam naar keuze. Lukt dat?

In [ ]:
mijn_dict["naam"] = "Raymond"

## Data klaarzetten

Zet de volgende bestanden in een makkelijk terug te vinden map:
- go_sales.sqlite
- go_crm.sqlite
- go_staff.sqlite

Bestudeer de bovenste 3 bestanden met DB Browser (SQLite) dat <a href="https://sqlitebrowser.org/dl/">hier</a> te downloaden is. Wat valt je op qua datatypen?<br>

## Databasetabel inlezen

Creëer een databaseconnectie met het bestand go_sales.sqlite. Let op: deze staat in de map "data", die op zijn beurt in de hoofdmap staat. Tip: met `"../"` in `connect()` kun je naar de bovenliggende map gaan.

In [3]:
connection = sqlite3.connect('Data/go_sales.sqlite')

<b>Let goed op:</b><br>
Als je per ongeluk een verkeerde bestandsnaam ingeeft, maakt Python zélf een leeg databasebestand aan! Er ontstaat dan dus een nieuwe .sqlite, en dat is nadrukkelijk <u>niet de bedoeling.</u>

Gebruik de onderstaande sql_query om te achterhalen welke databasetabellen in go_sales zitten.

In [4]:
sql_query = "SELECT name FROM sqlite_master WHERE type='table';"
sqlite_master = pd.read_sql(sql_query, connection)
sqlite_master

             name
0         country
1   order_details
2    order_header
3    order_method
4         product
5    product_line
6    product_type
7   retailer_site
8   return_reason
9   returned_item
10   sales_branch
11    sales_staff

Krijg je lege output? Dan heb je per ongeluk een leeg  databasebestand (.sqlite) aangemaakt.<br>
Lees de informatie onder het kopje <b>Let goed op:</b> hierboven nog eens goed door.

Gebruik de gecreëerde databaseconnectie om de resultaten van de volgende query in een DataFrame te zetten:<br>
*SELECT * FROM sales_staff*

In [ ]:
import sqlite3
import pandas as pd

conn_staff = sqlite3.connect('Data/go_staff.sqlite')

query = "SELECT * FROM sales_staff"
df_staff = pd.read_sql_query(query, conn_staff)

df_staff.head()

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,MANAGER_CODE
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6,18
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6,4
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6,4
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6,4
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13,14

## Datumkolommen afhandelen

Zoals je misschien al hebt gezien in DB Browser, zijn datums als TEXT opgeslagen, en niet als DATE, DATETIME o.i.d. Hier moeten we dus nog even "typische datumkolommen" van maken. Dat doen we met de volgende code:

In [22]:
sales_staff = pd.read_sql_query("SELECT * FROM sales_staff", conn_staff)

print(sales_staff.head())

sales_staff['DATE_HIRED'] = pd.to_datetime(sales_staff['DATE_HIRED'])

print(sales_staff.dtypes)

   SALES_STAFF_CODE FIRST_NAME  LAST_NAME                   POSITION_EN  \
0                 4      Denis       Pagé                Branch Manager
1                 5  Élizabeth     Michel  Level 3 Sales Representative
2                 6      Émile   Clermont  Level 1 Sales Representative
3                 7    Étienne     Jauvin  Level 2 Sales Representative
4                12    Elsbeth  Wiesinger  Level 2 Sales Representative

          WORK_PHONE  EXTENSION                FAX                   EMAIL  \
0  +33 1 68 94 52 20      325.0  +33 1 68 94 56 60       DPage@grtd123.com
1  +33 1 68 94 52 20      336.0  +33 1 68 94 56 60     EMichel@grtd123.com
2  +33 1 68 94 52 20      378.0  +33 1 68 94 56 60   EClermont@grtd123.com
3  +33 1 68 94 52 20      398.0  +33 1 68 94 56 60     EJauvin@grtd123.com
4  +(49) 40 663 1990     1818.0  +(49) 40 663 4571  EWiesinger@grtd123.com

   DATE_HIRED  SALES_BRANCH_CODE  MANAGER_CODE
0  1996-11-03                  6            18
1  1995-06-08                  6             4
2  1998-04-07                  6             4
3  1997-08-16                  6             4
4  1997-02-27                 13            14
SALES_STAFF_CODE              int64
FIRST_NAME                      str
LAST_NAME                       str
POSITION_EN                     str
WORK_PHONE                      str
EXTENSION                   float64
FAX                             str
EMAIL                           str
DATE_HIRED           datetime64[us]
SALES_BRANCH_CODE             int64
MANAGER_CODE                  int64
dtype: object

Als we hier het jaar uit willen halen, schrijven we:

In [11]:
pd.DatetimeIndex(sales_staff['DATE_HIRED']).year

Index([1996, 1995, 1998, 1997, 1997, 1999, 1997, 1998, 1996, 1996,
       ...
       1998, 2000, 1999, 2000, 1999, 1999, 1999, 1999, 1998, 1998],
      dtype='int32', name='DATE_HIRED', length=102)

Deze zelfde syntax is te gebruiken voor het extraheren van kwartalen, maanden, weken en dagen. Probeer het maar eens!

## DataFrames uitsplitsen en opbouwen met Series

De volgende 5 kolommen hebben betrekking op de contactdetails van elke medewerker in dit DataFrame:
- SALES_STAFF_CODE
- WORK_PHONE
- EXTENSION
- FAX
- EMAIL

Maak van elk van deze 5 kolommen een serie.

In [24]:
staff_code = sales_staff['SALES_STAFF_CODE']
phone = sales_staff['WORK_PHONE']
extension = sales_staff['EXTENSION']
fax = sales_staff['FAX']
email = sales_staff['EMAIL']

print(email.head())

0         DPage@grtd123.com
1       EMichel@grtd123.com
2     EClermont@grtd123.com
3       EJauvin@grtd123.com
4    EWiesinger@grtd123.com
Name: EMAIL, dtype: str

Zet allevijf gecreëerde series als kolommen naast elkaar in een DataFrame (*contact_details*). Gebruik pd.concat(...)<br>
Hulpvraag: welke waarde geef je aan de axis-parameter?

In [26]:
contact_details = pd.concat([staff_code, phone, extension, fax, email], axis=1)

contact_details.head()

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com

## Series en DataFrames maken vanuit lists en dictionaries

Met .head(*getal*) kan je de bovenste *getal* rijen van een tabel selecteren.<br>
Selecteer op deze manier de bovenste 5 rijen van *contact_details*.<br>
Sla dit resultaat op in een nieuw DataFrame.

In [ ]:
contact_details = pd.concat([staff_code, phone, extension, fax, email], axis=1)

contact_details_top5 = contact_details.head(5)

contact_details_top5

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com

Aan deze 10 rijen met contactdetails willen we 3 kolommen toevoegen: 'FIRST_LANGUAGE', 'SECOND_LANGUAGE' & 'THIRD_LANGUAGE'.<br>
Iedereens 'First Language' is Engels, afgekort 'EN'. Maak een lijst waarin 5x 'EN' staat.<br>
Converteer deze lijst vervolgens naar een serie en voeg deze horizontaal samen met het resultaat van de vorige opdracht.<br>
Vergeet niet een passende naam te geven aan de nieuw ontstane kolom.

In [39]:
first_language_list = ['EN', 'EN', 'EN', 'EN', 'EN']

first_language = pd.Series(first_language_list, name='FIRST_LANGUAGE')

contact_details = pd.concat([contact_details, first_language], axis=1)

contact_details.head()

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL,FIRST_LANGUAGE,SECOND_LANGUAGE,SECOND_LANGUAGE,THIRD_LANGUAGE,THIRD_LANGUAGE,SECOND_LANGUAGE,SECOND_LANGUAGE,SECOND_LANGUAGE,SECOND_LANGUAGE,SECOND_LANGUAGE,FIRST_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN,FR,FR,NL,NL,FR,FR,FR,FR,FR,EN
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN,FR,FR,NL,NL,FR,FR,FR,FR,FR,EN
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN,FR,FR,JPN,JPN,FR,FR,FR,FR,FR,EN
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN,DE,DE,JPN,JPN,DE,DE,DE,DE,DE,EN
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN,DE,DE,KOR,KOR,DE,DE,DE,DE,DE,EN

Maak nu de tweede kolom ('SECOND_LANGUAGE'). Maak daarvoor een dictionary, met daarin...
- Als keys: alle indexen uit het resultaat van het vorige codeblok.
- Als values: bij de eerste 3 elementen 'FR' (Frankrijk), bij de laatste 2 'DE' (Duitsland).

Maak vervolgens ook hier weer een serie van en voeg ook deze weer horizontaal samen met het rsultaat van de vorige opdracht.<br>
Vergeet niet een passende naam te geven aan de nieuw ontstane kolom.

In [38]:
second_language_dict = {
    0: 'FR', 
    1: 'FR', 
    2: 'FR', 
    3: 'DE', 
    4: 'DE'
}

second_language = pd.Series(second_language_dict, name='SECOND_LANGUAGE')

contact_details = pd.concat([contact_details, second_language], axis=1)

contact_details.head()

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL,FIRST_LANGUAGE,SECOND_LANGUAGE,SECOND_LANGUAGE,THIRD_LANGUAGE,THIRD_LANGUAGE,SECOND_LANGUAGE,SECOND_LANGUAGE,SECOND_LANGUAGE,SECOND_LANGUAGE,SECOND_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN,FR,FR,NL,NL,FR,FR,FR,FR,FR
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN,FR,FR,NL,NL,FR,FR,FR,FR,FR
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN,FR,FR,JPN,JPN,FR,FR,FR,FR,FR
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN,DE,DE,JPN,JPN,DE,DE,DE,DE,DE
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN,DE,DE,KOR,KOR,DE,DE,DE,DE,DE

Maak ten slotte de derde kolom ('THIRD_LANGUAGE') door een dictionary te maken met daarin...
- Als key: de naam van de nieuwe kolom. Zie je het verschil qua keys met de vorige opdracht?
- Als waarde: een lijst met daarin 'NL', 'NL', 'JPN', 'JPN', 'KOR'.

Converteer deze dictionary nu naar een DataFrame en voeg deze horizontaal samen met het resultaat van de vorige opdracht.<br>
Waarom hoef je hierna de nieuw ontstane kolom geen passende naam meer te geven?

In [32]:
third_lang_dict = {
    'THIRD_LANGUAGE': ['NL', 'NL', 'JPN', 'JPN', 'KOR']
}

third_language = pd.DataFrame(third_lang_dict)

contact_details = pd.concat([contact_details, third_language], axis=1)

contact_details.head()

,SALES_STAFF_CODE,WORK_PHONE,EXTENSION,FAX,EMAIL,FIRST_LANGUAGE,SECOND_LANGUAGE,SECOND_LANGUAGE,THIRD_LANGUAGE,THIRD_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN,FR,FR,NL,NL
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN,FR,FR,NL,NL
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN,FR,FR,JPN,JPN
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN,DE,DE,JPN,JPN
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN,DE,DE,KOR,KOR

## Data toevoegen

### Rijen

Gebruik de originele databasetabel *sales_staff*.<br>
Voeg een extra rij toe met eigen invulling. Zorg ervoor dat de index netjes doorloopt.<br>
Hulpvraag: welke waarde geef je nu aan axis?

In [40]:
nieuwe_collega = pd.DataFrame({
    'SALES_STAFF_CODE': [999],
    'FIRST_NAME': ['JouwNaam'],
    'LAST_NAME': ['Achternaam'],
    'POSITION_EN': ['Data Analyst'],
    'WORK_PHONE': ['0612345678'],
    'EXTENSION': [123],
    'FAX': ['010-123456'],
    'EMAIL': ['test@email.com'],
    'DATE_HIRED': [pd.to_datetime('2023-01-01')],
    'SALES_BRANCH_CODE': [1]
})

sales_staff = pd.concat([sales_staff, nieuwe_collega], axis=0, ignore_index=True)

sales_staff.tail()

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,MANAGER_CODE
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com,1999-12-01,38,119.0
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com,1999-12-09,38,119.0
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,1998-10-28,39,18.0
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39,18.0
102,999,JouwNaam,Achternaam,Data Analyst,0612345678,123.0,010-123456,test@email.com,2023-01-01,1,NaN

### Kolommen

Voeg een kolom *FULL_NAME* toe die de waarden van *FIRST_NAME* en *LAST_NAME* achter elkaar zet, gescheiden door een spatie.

In [41]:
sales_staff['FULL_NAME'] = sales_staff['FIRST_NAME'] + ' ' + sales_staff['LAST_NAME']

sales_staff[['FIRST_NAME', 'LAST_NAME', 'FULL_NAME']].head()

  FIRST_NAME  LAST_NAME          FULL_NAME
0      Denis       Pagé         Denis Pagé
1  Élizabeth     Michel   Élizabeth Michel
2      Émile   Clermont     Émile Clermont
3    Étienne     Jauvin     Étienne Jauvin
4    Elsbeth  Wiesinger  Elsbeth Wiesinger

## Data wijzigen

### Datatypen

Door het attribuut .dtypes van een DataFrame op te vragen krijg je een serie die per kolom het datatype weergeeft. Doe dit bij de originele databasetabel *sales_staff*

In [43]:
sales_staff.dtypes

SALES_STAFF_CODE              int64
FIRST_NAME                      str
LAST_NAME                       str
POSITION_EN                     str
WORK_PHONE                      str
EXTENSION                   float64
FAX                             str
EMAIL                           str
DATE_HIRED           datetime64[us]
SALES_BRANCH_CODE             int64
MANAGER_CODE                float64
FULL_NAME                       str
dtype: object

Hier valt op dat elke kolom het datatype 'object' heeft: Python leest dus alles als string. Wiskundige operaties zijn hierdoor niet mogelijk.<br>
We kunnen proberen om kolommen met getallen, bijvoorbeeld de 'extension', te converteren naar een int. Zie onderstaande code.

In [50]:
sales_staff['EXTENSION'] = pd.to_numeric(sales_staff['EXTENSION'], errors='coerce').astype('Int64')


print(sales_staff['EXTENSION'].dtypes)

Int64

Dit lukt echter niet, omdat er in de kolom 'EXTENSION' lege waarden zitten die niet geconverteerd kunnen worden naar een int.<br>
Wél kan je deze naar een float converteren, zie onderstaande code:

In [48]:

sales_staff['EXTENSION'] = sales_staff['EXTENSION'].astype(float)


sales_staff.dtypes

SALES_STAFF_CODE              int64
FIRST_NAME                      str
LAST_NAME                       str
POSITION_EN                     str
WORK_PHONE                      str
EXTENSION                   float64
FAX                             str
EMAIL                           str
DATE_HIRED           datetime64[us]
SALES_BRANCH_CODE             int64
MANAGER_CODE                float64
FULL_NAME                       str
dtype: object

Als we in de rij van 'EXTENSION' kijken zien we dat de conversie van het datatype nu is gelukt.<br>
Dit is <b>randvoorwaardelijk</b> voor het uitvoeren van wiskundige operaties.<br>

### Rijen

Zorg er nu voor dat bij alle extensions 1 wordt opgeteld.

In [51]:
sales_staff['EXTENSION'] = sales_staff['EXTENSION'] + 1

sales_staff[['FIRST_NAME', 'LAST_NAME', 'EXTENSION']].head()

  FIRST_NAME  LAST_NAME  EXTENSION
0      Denis       Pagé        326
1  Élizabeth     Michel        337
2      Émile   Clermont        379
3    Étienne     Jauvin        399
4    Elsbeth  Wiesinger       1819

Elke 'Branch Manager' wordt nu 'General Manager'. Schrijf code zodat deze wijziging doorgevoerd wordt in het DataFrame.

In [53]:
sales_staff['POSITION_EN'] = sales_staff['POSITION_EN'].replace('Branch Manager', 'General Manager')

sales_staff[sales_staff['POSITION_EN'] == 'General Manager'].head()

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,MANAGER_CODE,FULL_NAME
0,4,Denis,Pagé,General Manager,+33 1 68 94 52 20,326,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6,18.0,Denis Pagé
6,14,Frank,Fuchs,General Manager,+(49) 40 663 1990,1848,+(49) 40 663 4571,FFuchs@grtd123.com,1997-01-12,13,18.0,Frank Fuchs
9,17,Fritz,Hirsch,General Manager,+(49) 89 882 3456,226,+(49) 89 882 3455,FHirsch@grtd123.com,1996-09-12,14,18.0,Fritz Hirsch
12,20,Maria,Iacobucci,General Manager,+(39) 02 41 05 400,<NA>,+(39) 02 41 20 549,MIacobucci@grtd123.com,1996-08-18,7,18.0,Maria Iacobucci
17,25,Kick,Kalkman,General Manager,+31 (0)20 692 93 94,198,+31 (0)20 692 93 06,KKalkman@grtd123.com,1995-09-06,9,18.0,Kick Kalkman

### Kolommen

Verander de kolomnaam 'POSITION_EN' naar 'POSITION'.

In [54]:
sales_staff = sales_staff.rename(columns={'POSITION_EN': 'POSITION'})

sales_staff.columns

Index(['SALES_STAFF_CODE', 'FIRST_NAME', 'LAST_NAME', 'POSITION', 'WORK_PHONE',
       'EXTENSION', 'FAX', 'EMAIL', 'DATE_HIRED', 'SALES_BRANCH_CODE',
       'MANAGER_CODE', 'FULL_NAME'],
      dtype='str')

## Data verwijderen

### Rijen

De medewerkers op indexen 98, 99 en 100 hebben helaas ontslag genomen.<br>
Verwijder de bijbehorende rijen uit het DataFrame. Gebruik slechts één keer de .drop()-methode.

In [58]:
sales_staff = sales_staff.drop([98, 99, 100])

KeyError: '[98, 99, 100] not found in axis'

### Kolommen

Faxen zijn inmiddels ouderwets: niemand gebruikt zijn/haar faxnummer nog.<br>
Verwijder de bijbehorende kolom uit het DataFrame.

In [59]:
sales_staff = sales_staff.drop(columns=['FAX'])

sales_staff.head()

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION,WORK_PHONE,EXTENSION,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,MANAGER_CODE,FULL_NAME
0,4,Denis,Pagé,General Manager,+33 1 68 94 52 20,326,DPage@grtd123.com,1996-11-03,6,18.0,Denis Pagé
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,337,EMichel@grtd123.com,1995-06-08,6,4.0,Élizabeth Michel
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,379,EClermont@grtd123.com,1998-04-07,6,4.0,Émile Clermont
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,399,EJauvin@grtd123.com,1997-08-16,6,4.0,Étienne Jauvin
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1819,EWiesinger@grtd123.com,1997-02-27,13,14.0,Elsbeth Wiesinger