In [3]:
import sqlite3
import pandas as pd

# Testen of we wel de tabellen hebben.
conn = sqlite3.connect('./SDM.db')

data = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
data

                              name
0   Accessoire_Verkoop_Leverancier
1       Accessoire_Verkoop_Filiaal
2         Accessoire_Verkoop_Klant
3    Accessoire_Verkoop_Accessoire
4       Accessoire_Verkoop_Monteur
5               Accessoire_Verkoop
6               Fietsverkoop_Klant
7             Fietsverkoop_Filiaal
8               Fietsverkoop_Fiets
9                    Fiets_Verkoop
10             Onderhoud_Fabrikant
11                 Onderhoud_Fiets
12               Onderhoud_Filiaal
13               Onderhoud_Monteur
14                       Onderhoud
15   Accessoire_Inkoop_Leverancier
16    Accessoire_Inkoop_Accessoire
17               Accessoire_Inkoop
18          Fiets_Inkoop_Fabrikant
19              Fiets_Inkoop_Fiets
20                    Fiets_Inkoop

In [4]:
# We gebruiken de methode 'Full-refresh'. Binnen deze methode gaan we alle data verwijderen en dat dan terughalen.
def reset_sdm():
    try:
        conn = sqlite3.connect('SDM.db')
        cursor = conn.cursor()
        # Haal alle tabellen op
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        tabellen = [t[0] for t in cursor.fetchall()]

        #Met de for loop wordt de data verwijderd
        for tabel in tabellen:
            cursor.execute(f"DELETE FROM {tabel}")

        conn.commit()
        conn.close()
        print("Reset geslaagd! Alle tabellen zijn leeg.")
    except Exception as e:
        print(f"Fout bij reset: {e}")

reset_sdm()

Reset geslaagd! Alle tabellen zijn leeg.

                              name
0   Accessoire_Verkoop_Leverancier
1       Accessoire_Verkoop_Filiaal
2         Accessoire_Verkoop_Klant
3    Accessoire_Verkoop_Accessoire
4       Accessoire_Verkoop_Monteur
5               Accessoire_Verkoop
6               Fietsverkoop_Klant
7             Fietsverkoop_Filiaal
8               Fietsverkoop_Fiets
9                    Fiets_Verkoop
10             Onderhoud_Fabrikant
11                 Onderhoud_Fiets
12               Onderhoud_Filiaal
13               Onderhoud_Monteur
14                       Onderhoud
15   Accessoire_Inkoop_Leverancier
16    Accessoire_Inkoop_Accessoire
17               Accessoire_Inkoop
18          Fiets_Inkoop_Fabrikant
19              Fiets_Inkoop_Fiets
20                    Fiets_Inkoop