# Werkcollege-opdrachten Week 1.3

## Dependencies importeren

Kopieer in het codeblok hieronder van het vorige werkcollege de import-code voor de dependencies die het vaakst worden gebruikt om data in te lezen. Geef er ook de gebruikelijke aliassen aan.<br>
Zet eventuele warnings uit.

In [2]:
import pandas as pd
import sqlite3
import warnings
import numpy as np
warnings.simplefilter('ignore')

Zet de volgende bestanden in een makkelijk te vinden map, als je dat nog niet gedaan hebt:
- go_sales.sqlite
- go_crm.sqlite
- go_staff.sqlite

## Databasetabellen inlezen

Kopieer in het codeblok hieronder van het vorige werkcollege de code om een connectie met het bestand go_sales.sqlite te maken.

In [ ]:
con = sqlite3.connect('./go_sales.sqlite')

Hello A😁
0
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello A😁
1
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello A😁
2
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello A😁
3
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello A😁
4
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello A😁
5
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello A😁
6
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello A😁
7
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello A😁
8
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello A😁
9
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello B ☺️
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭
Hello C 😭

1000

Lees van de ingelezen go_sales-database te volgende tabellen in met behulp van "SELECT * FROM *tabel*".
- product
- product_type
- product_line
- sales_staff
- sales_branch
- retailer_site
- country
- order_header
- order_details
- returned_item
- return_reason

In [4]:
query = "SELECT * FROM sales_staff"
sales_staff = pd.read_sql_query(query, con)
sales_staff

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13
...,...,...,...,...,...,...,...,...,...,...
97,120,Giele,Laermans,Level 1 Sales Representative,+32 16 20.73.21,1340.0,+32 16 20.73.32,GLaermans@grtd123.com,1999-11-15,38
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com,1999-12-01,38
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com,1999-12-09,38
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,1998-10-28,39
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39

Krijg je een "no such table" error? Dan heb je misschien met .connect() per ongeluk een leeg  databasebestand (.sqlite) aangemaakt.<br> <u>Let op:</u> lees eventueel de informatie uit het vorige werkcollege nog eens goed door.

Als je tijdens onderstaande opdrachten uit het oog verliest welke tabellen er allemaal zijn, kan je deze Pythoncode uitvoeren:

In [5]:
sql_query = "SELECT * FROM sqlite_master WHERE type='table';"
#Vul dit codeblok verder in
pd.read_sql(sql_query, con)
#Op de puntjes hoort de connectie naar go_sales óf go_staff óf go_crm te staan.

,type,name,tbl_name,rootpage,sql
0,table,country,country,480,"CREATE TABLE ""country"" (\n\t""COUNTRY_CODE""\tIN..."
1,table,order_details,order_details,11,"CREATE TABLE ""order_details"" (\n\t""ORDER_DETAI..."
2,table,order_header,order_header,24,"CREATE TABLE ""order_header"" (\n\t""ORDER_NUMBER..."
3,table,order_method,order_method,27,"CREATE TABLE ""order_method"" (\n\t""ORDER_METHOD..."
4,table,product,product,28,"CREATE TABLE ""product"" (\n\t""PRODUCT_NUMBER""\t..."
5,table,product_line,product_line,17,"CREATE TABLE ""product_line"" (\n\t""PRODUCT_LINE..."
6,table,product_type,product_type,10,"CREATE TABLE ""product_type"" (\n\t""PRODUCT_TYPE..."
7,table,retailer_site,retailer_site,18,"CREATE TABLE ""retailer_site"" (\n\t""RETAILER_SI..."
8,table,return_reason,return_reason,30,"CREATE TABLE ""return_reason"" (\n\t""RETURN_REAS..."
9,table,returned_item,returned_item,31,"CREATE TABLE ""returned_item"" (\n\t""RETURN_CODE..."
10,table,sales_branch,sales_branch,2,"CREATE TABLE ""sales_branch"" (\n\t""SALES_BRANCH..."
11,table,sales_staff,sales_staff,3,"CREATE TABLE ""sales_staff"" (\n\t""SALES_STAFF_C..."

Let op! Voor alle onderstaande opdrachten mag je <u>alleen Python</u> gebruiken, <u>geen SQL!</u>

## Selecties op één tabel zonder functies

Geef een overzicht met daarin de producten en hun productiekosten waarvan de productiekosten lager dan 100 dollar en hoger dan 50 dollar ligt. (2 kolommen, 23 rijen)

In [ ]:
product_query = pd.read_sql_query("SELECT * FROM product", con)

# Between kun je gebruiken
result = product_query.loc[product_query['PRODUCTION_COST'].between(50, 100)]
result

# # Test
result_test = product_query.loc[:, ['PRODUCT_NUMBER', 'PRODUCT_NAME']]
print(type(result_test))

,PRODUCT_NUMBER,INTRODUCTION_DATE,PRODUCT_TYPE_CODE,PRODUCTION_COST,MARGIN,PRODUCT_IMAGE,LANGUAGE,PRODUCT_NAME,DESCRIPTION
5,6,1997-03-05,1,85.11,0.28,P06CE1CG1.jpg,EN,TrailChef Deluxe Cook Set,"Cascade set features 1, 2, and 3 liter pots wi..."
7,8,1997-03-05,1,75.00,0.41,P08CE1CG1.jpg,EN,TrailChef Double Flame,The TrailChef Double Flame is a camp stove whi...
16,17,1997-03-05,3,60.00,0.28,P17CE1SB3.jpg,EN,Hibernator Lite,The Hibernator Lite is the perfect summer slee...
17,18,1995-02-15,3,86.00,0.33,P17CE1SB3.jpg,EN,Hibernator,The Hibernator is a three-season sleeping bag....
19,20,1997-03-05,3,78.55,0.28,P20CE1SB3.jpg,EN,Hibernator Self - Inflating Mat,Mattress is made of extra-thick foam. Mesh stu...
22,23,1997-03-05,3,65.33,0.33,P23CE1SB3.jpg,EN,Hibernator Camp Cot,Aluminum frame camp cot that is lightweight an...
23,24,1997-03-05,4,62.50,0.17,P24CE1PK4.jpg,EN,Canyon Mule Climber Backpack,This pack is perfect for day trips and short h...
45,46,2005-01-10,7,52.86,0.28,P46ME2SY7.jpg,EN,Granite Climbing Helmet,This UIAA approved helmet fits adults and kids...
47,48,2005-01-10,7,55.00,0.50,P47ME2SY7.jpg,EN,Husky Harness Extreme,One size fits all. Top of the range fully adju...
57,58,2005-01-10,9,57.13,0.28,P58ME2TL9.jpg,EN,Granite Hammer,A solid hammer made with a solid hard wood han...
68,69,1995-02-15,11,73.33,0.33,P69PA3EW11.jpg,EN,Polar Ice,Polar Ice sunglasses have polarized lenses to ...
69,70,1997-03-05,11,80.00,0.33,P70PA3EW11.jpg,EN,Polar Sports,Six base classic nylon composite frame sunglas...
70,71,1997-03-05,11,60.00,0.33,P71PA3EW11.jpg,EN,Polar Wave,Acrylex lenses in the Polar Wave sunglasses ab...
71,72,2000-10-26,11,72.50,0.50,P72PA3EW11.jpg,EN,Polar Extreme,Ideal for skiing and winter mountaineering. Fr...
74,75,2000-10-26,12,80.00,0.28,P75PA3KV12.jpg,EN,Edge Extreme,Multi-purpose pocketknife ruggedly constructed...
77,78,1995-02-15,13,79.19,0.20,P78PA3BN13.jpg,EN,Seeker 35,This 7 x 35 model is economical and performs w...
78,79,1995-02-15,13,92.58,0.25,P78PA3BN13.jpg,EN,Seeker 50,Rubber coated and ergonomically designed. The ...
79,80,1997-03-05,13,94.12,0.40,P80PA3BN13.jpg,EN,Seeker Extreme,These ergonomic binoculars are light-weight an...
82,83,1997-03-05,14,56.25,0.37,P83PA3NV14.jpg,EN,Glacier Deluxe,Magnetic Compass has a large sighting mirror w...
83,84,1997-03-05,14,78.55,0.28,P84PA3NV14.jpg,EN,Glacier GPS,"Global Positioning System that is small, light..."
109,110,2003-12-10,20,60.00,0.50,P110GE5PT20.jpg,EN,Blue Steel Putter,This premium putter has copper mixed with ligh...
110,111,2003-12-15,20,81.80,0.55,P111GE5PT20.jpg,EN,Blue Steel Max Putter,Putter head is composed from a single piece of...
113,114,2003-12-15,21,80.00,0.60,P114GE5GA21.jpg,EN,Course Pro Golf Bag,High quality golf bag that includes carrying s...

Geef een overzicht met daarin de producten en hun marge waarvan de marge lager dan 20 % of hoger dan 60 % ligt. (2 kolommen, 7 rijen)

In [7]:
# De product_query is de dataframe
result_statement = product_query.loc[
    # De product_query['MARGIN'] is de Serie die je wilt oproepen om te vergelijken
    (product_query['MARGIN'] < 0.20) |
    (product_query['MARGIN'] > 0.60)
    ]

print(type(result_statement))
result = result_statement.loc[:, ['PRODUCT_NAME', 'MARGIN']]
result

<class 'pandas.DataFrame'>

                    PRODUCT_NAME  MARGIN
20                Hibernator Pad    0.17
23  Canyon Mule Climber Backpack    0.17
85             BugShield Natural    0.67
86               BugShield Spray    0.67
87         BugShield Lotion Lite    0.70
88              BugShield Lotion    0.63
89             BugShield Extreme    0.63

Geef een overzicht met daarin de landen waar met francs wordt betaald. Sorteer de uitkomst op land.  (1 kolom, 3 rijen)

In [8]:
country_query = pd.read_sql_query("SELECT * FROM COUNTRY", con)
country_query
product_query

,PRODUCT_NUMBER,INTRODUCTION_DATE,PRODUCT_TYPE_CODE,PRODUCTION_COST,MARGIN,PRODUCT_IMAGE,LANGUAGE,PRODUCT_NAME,DESCRIPTION
0,1,1995-02-15,1,4.00,0.33,P01CE1CG1.jpg,EN,TrailChef Water Bag,"Lightweight, collapsible bag to carry liquids ..."
1,2,1995-02-15,1,9.22,0.23,P02CE1CG1.jpg,EN,TrailChef Canteen,Aluminum canteen. Rugged fleece-lined cover wi...
2,3,1995-02-15,1,15.93,0.28,P03CE1CG1.jpg,EN,TrailChef Kitchen Kit,"Zippered nylon pouch contains cutlery for two,..."
3,4,1995-02-15,1,5.00,0.28,P04CE1CG1.jpg,EN,TrailChef Cup,Tin cup. Holds 0.4 liters. Weight: 60 g
4,5,1995-02-15,1,34.97,0.30,P05CE1CG1.jpg,EN,TrailChef Cook Set,All you will ever need on the trail. Pot grip...
...,...,...,...,...,...,...,...,...,...
110,111,2003-12-15,20,81.80,0.55,P111GE5PT20.jpg,EN,Blue Steel Max Putter,Putter head is composed from a single piece of...
111,112,2004-01-10,21,6.00,0.33,P112GE5GA21.jpg,EN,Course Pro Golf and Tee Set,Set includes two premium golf ball and an asso...
112,113,2004-01-15,21,6.00,0.50,P113GE5GA21.jpg,EN,Course Pro Umbrella,Large red and white patterned golf umbrella.
113,114,2003-12-15,21,80.00,0.60,P114GE5GA21.jpg,EN,Course Pro Golf Bag,High quality golf bag that includes carrying s...
114,115,2003-12-27,21,5.00,0.50,P115GE5GA21.jpg,EN,Course Pro Gloves,Durable nylon constructed gloves with stitched...

Geef een overzicht met daarin de verschillende introductiedatums waarop producten met meer dan 50% marge worden geïntroduceerd (1 kolom, 7 rijen)

In [ ]:
product_query
# Eerst checken wanneer de marge meer is dan 50%
check_marge = product_query.loc[product_query['MARGIN'] > 0.50]

# toont de dates
show_introduction_date = check_marge['INTRODUCTION_DATE'].drop_duplicates()
result = pd.DataFrame(show_introduction_date)

66     2000-10-26
85     1995-02-15
101    2003-12-10
103    2003-12-18
104    2003-12-27
106    2004-01-13
110    2003-12-15
Name: INTRODUCTION_DATE, dtype: str

Geef een overzicht met daarin het eerste adres en de stad van verkoopafdelingen waarvan zowel het tweede adres als de regio bekend is (2 kolommen, 7 rijen)

In [39]:
staff_branch = pd.read_sql_query("SELECT * FROM sales_branch", con)
staff_branch

eerste_adres_en_stad = staff_branch.loc[:, ['ADDRESS1', 'CITY']]
eerste_adres_en_stad

tweede_adres_en_regio = staff_branch.loc[:, ['ADDRESS2', 'REGION']]
tweede_adres_en_regio

beide_addressen = staff_branch.loc[:, ['ADDRESS1', 'CITY', 'ADDRESS2', 'REGION']]
beide_addressen.head(7)

                        ADDRESS1       CITY       ADDRESS2         REGION
0  75, rue du Faubourg St-Honoré      Paris            NaN            NaN
1                Piazza Duomo, 1     Milano            NaN            NaN
2            Singelgravenplein 4  Amsterdam  4e verdieping  Noord-Holland
3                 Schwabentor 35    Hamburg            NaN            NaN
4               Leopoldstraße 36    München            NaN            NaN
5            Isafjordsgatan 30 C      Kista            NaN            NaN
6   7800, 756 - 6th Avenue. S.W.    Calgary            NaN        Alberta

Geef een overzicht met daarin de landen waar met dollars (dollars of new dollar) wordt betaald. Sorteer de uitkomst op land. (1 kolom, 4 rijen)

In [38]:
country = pd.read_sql_query("SELECT * FROM country", con)
sales_branch = pd.read_sql_query("SELECT * FROM sales_branch", con)

# OUTER JOIN, om alle dingen te zien.
sb_to_c = pd.merge(sales_branch, country, left_on='COUNTRY_CODE', how='outer', right_on='COUNTRY_CODE')

dollar_landen = sb_to_c[sb_to_c['CURRENCY_NAME'].str.contains('dollar')]

resultaat = (
    dollar_landen[['COUNTRY']]
    .drop_duplicates()
    .sort_values(by='COUNTRY')
    .reset_index(drop=True)
)

resultaat

# country_with_dollar = staff_branch['COUNTRY_CODE'] == 3
# staff_branch.loc[(country_with_dollar), :]

         COUNTRY
0      Australia
1         Canada
2         Taiwan
3  United States

Geef een overzicht met daarin beide adressen en de stad van vestigingen van klanten waarvan de postcode begint met een ‘D’ (van duitsland). Filter op vestigingen die een tweede adres hebben. (3 kolommen, 2 rijen)

In [12]:
retailer_site = pd.read_sql_query("SELECT * FROM retailer_site", con)

# beide addressen, de stad van klanten en postcode met D
beide_addressen_data = retailer_site.loc[:, ['ADDRESS1', 'ADDRESS2', 'CITY']]

# De like statement
postcode_met_een_d = retailer_site['POSTAL_ZONE'].str[0] == 'D'

# Nadat de 'like' is gedaan, wordt het gecombineerd
beide_addressen_data.loc[(postcode_met_een_d), :].head(2)

              ADDRESS1       ADDRESS2       CITY
31    Röntgenstraße 90  3. Tür rechts  Frankfurt
32  Mathildenstraße 67            NaN     Berlin

## Selecties op één tabel met functies

Geef het totaal aantal producten dat is teruggebracht (1 waarde)

In [13]:
product_query = pd.read_sql_query("SELECT * FROM Product", con)
returned_item_query = pd.read_sql_query("SELECT * FROM returned_item", con)

quantity_waarde_een = returned_item_query['RETURN_QUANTITY'].sum()

returned_item_query.groupby('RETURN_CODE', as_index = False)['RETURN_QUANTITY'].agg([sum, np.mean])

     RETURN_CODE  sum  mean
0           1491    8   8.0
1           1492    2   2.0
2           1493   22  22.0
3           1494   20  20.0
4           1496    2   2.0
..           ...  ...   ...
614         2464   12  12.0
615         2465   24  24.0
616         2466   66  66.0
617         2467   64  64.0
618         2469   82  82.0

[619 rows x 3 columns]

Geef het aantal regio’s waarin verkoopafdelingen gevestigd zijn. (1 waarde)

In [14]:
sales_branch_query = pd.read_sql_query("SELECT * FROM sales_branch", con)
sales_branch_query = sales_branch_query['REGION'].unique()
print(type(sales_branch_query))

<class 'pandas.arrays.StringArray'>

Maak 3 variabelen:
- Een met de laagste
- Een met de hoogste
- Een met de gemiddelde (afgerond op 2 decimalen)

marge van producten (3 kolommen, 1 rij)

In [15]:
# Hergebruik dit
product_query

laagste_marge = product_query['MARGIN'].min()
hoogste_marge = product_query['MARGIN'].max()
# Binnen Panda heb je helaas geen '.avg()'
gemiddelde_marge = round(product_query['MARGIN'].mean(), 2)

# Hiervan maak ik een dataframe van de waardes die ik wil weten
df_min = pd.DataFrame({'laagste_marge': [laagste_marge]})
df_max = pd.DataFrame({'hoogste_marge': [hoogste_marge]})
df_avg = pd.DataFrame({'gemiddelde_marge': [gemiddelde_marge]})

# Nadat ik apart waardes gemaakt heb, ga ik het samen toevoegen
df_min['key'] = 0
df_max['key'] = 0
df_avg['key'] = 0

# Hier merge ik de waardes
resultaat = pd.merge(df_min, df_max, on='key')
# Ik heb de df_avg apart gezet met de bovenste resultaat. Geen idee waarom het misgaat
resultaat = pd.merge(resultaat, df_avg, on='key')

# Omdat de key in weg staat, haal ik dat weg.
resultaat = resultaat.drop(columns='key')

print(resultaat)

   laagste_marge  hoogste_marge  gemiddelde_marge
0           0.17            0.7               0.4

Geef het aantal vestigingen van klanten waarvan het 2e adres niet bekend is (1 waarde)

In [16]:
customer_query= pd.read_sql_query("SELECT * FROM sales_branch", con)

# .isna() zorgt ervoor dat een attribuut niet meegegeven wordt
aantal_vestigingen = customer_query['ADDRESS2'].isna().sum()
aantal_vestigingen

np.int64(19)

Geef de gemiddelde kostprijs van de verkochte producten waarop korting (unit_sale_price < unit_price) is verleend (1 waarde)

In [17]:
sales_query = pd.read_sql_query("SELECT * FROM order_details", con)

# Filterd alleen de korting
korting_df = sales_query[sales_query['UNIT_SALE_PRICE'] < sales_query['UNIT_PRICE']]

# Gemiddelde kostprijs berekenen
gemiddelde_kostprijs = round(korting_df['UNIT_COST'].mean(), 2)

gemiddelde_kostprijs

np.float64(127.34)

Geef een overzicht met daarin het aantal medewerkers per medewerkersfunctie (2 kolommen, 7 rijen)

In [18]:
employee_df = pd.read_sql_query("SELECT * FROM sales_staff", con)

overzicht = (
    employee_df
    # De groupby groepeert de posities van de werknemers binnen de werknemer tabel
    .groupby('POSITION_EN')

    # Binnen de groupby tel je de rijen per groep op. Eigenlijk net als een count, maar dan voor 'rows' per functie
    .size()
    # !KAN NIET ZONDER size of andere panda functies die ik nog niet ken! 
    # voor de cherry on top, kan je ook een naam geven voor een tabel.
    .reset_index(name='aantal_medewerkers')
)

overzicht

                    POSITION_EN  aantal_medewerkers
0                Branch Manager                  19
1              District Manager                   4
2               General Manager                   1
3  Level 1 Sales Representative                  13
4  Level 2 Sales Representative                  39
5  Level 3 Sales Representative                  24
6              Regional Manager                   2

Geef een overzicht met daarin per telefoonnummer het aantal medewerkers dat op dat telefoonnummer bereikbaar is. Toon alleen de telefoonnummer waarop meer dan 4 medewerkers bereikbaar zijn. (2 kolommen, 10 rijen)

In [19]:
medewerkers_query = pd.read_sql_query("SELECT * FROM sales_staff", con)

# Zelfde als de vorige opdracht
overzicht = (medewerkers_query.groupby('WORK_PHONE').size().reset_index(name='Aantal Medewerkers'))

# Maar dan moet je binnen de dataframe, de serie oproepen en de waardes vergelijken
toon_overzicht_van_4_mensen = overzicht.loc[overzicht['Aantal Medewerkers'] > 4]
toon_overzicht_van_4_mensen

             WORK_PHONE  Aantal Medewerkers
4     +(44) 121 3505267                   5
10  +(61) 03 2982  4242                   5
11  +31 (0)20 692 93 94                   5
13    +33 1 68 94 52 20                   5
18     1 (206) 292-0012                   5
19     1 (305) 557-4810                   6
20     1 (310) 281-5722                   5
21     1 (403) 232-5986                   5
22     1 (416) 493-5595                   5
23     1 (617) 268-6754                   6

## Selecties op meerdere tabellen zonder functies

Geef een overzicht met daarin het eerste adres en de stad van vestigingen van klanten uit ‘Netherlands’ (2 kolommen, 20 rijen)

In [20]:
branch_query = pd.read_sql_query("SELECT * FROM sales_branch", con)
country_query = pd.read_sql_query("SELECT * FROM country", con)

# Tabellen koppelen
# pd.merge lijkt veel op de joins van sql
merged_df = pd.merge(branch_query, country_query, how='inner', on='COUNTRY_CODE')

# Filteren op Netherlands
nl_branches = merged_df[merged_df['COUNTRY'] == 'Netherlands']

# Alleen gevraagde kolommen
resultaat = nl_branches[['ADDRESS1', 'CITY']]

resultaat

              ADDRESS1       CITY
2  Singelgravenplein 4  Amsterdam

Geef een overzicht met daarin de productnamen die tot het producttype ‘Eyewear’ behoren. (1 kolom, 5 rijen)

In [21]:
product_query = pd.read_sql_query("SELECT * FROM product", con)
product_type_query = pd.read_sql_query("SELECT * FROM product_type", con)

merge_product = pd.merge(product_query, product_type_query, how='inner', on='PRODUCT_TYPE_CODE')
result = merge_product.loc[merge_product['PRODUCT_TYPE_EN'].str.contains('Eyewear')]

result

,PRODUCT_NUMBER,INTRODUCTION_DATE,PRODUCT_TYPE_CODE,PRODUCTION_COST,MARGIN,PRODUCT_IMAGE,LANGUAGE,PRODUCT_NAME,DESCRIPTION,PRODUCT_LINE_CODE,PRODUCT_TYPE_EN
67,68,1995-02-15,11,46.15,0.23,P68PA3EW11.jpg,EN,Polar Sun,The Polar Sun sunglasses have 3 mm thick lense...,3,Eyewear
68,69,1995-02-15,11,73.33,0.33,P69PA3EW11.jpg,EN,Polar Ice,Polar Ice sunglasses have polarized lenses to ...,3,Eyewear
69,70,1997-03-05,11,80.00,0.33,P70PA3EW11.jpg,EN,Polar Sports,Six base classic nylon composite frame sunglas...,3,Eyewear
70,71,1997-03-05,11,60.00,0.33,P71PA3EW11.jpg,EN,Polar Wave,Acrylex lenses in the Polar Wave sunglasses ab...,3,Eyewear
71,72,2000-10-26,11,72.50,0.50,P72PA3EW11.jpg,EN,Polar Extreme,Ideal for skiing and winter mountaineering. Fr...,3,Eyewear

Geef een overzicht met daarin alle unieke eerste adressen van klantvestigingen en de voornaam en achternaam van de verkopers die ‘Branch Manager’ zijn en aan deze vestigingen hebben verkocht (3 kolommen, 1 rij)

In [22]:
staff_query = pd.read_sql_query("SELECT * FROM sales_staff", con)

branch_managers = staff_query.loc[staff_query['POSITION_EN'].str.contains('Branch Manager')]

merge_all = pd.merge(branch_managers, branch_query, how='inner', on='SALES_BRANCH_CODE')

# De .drop_duplicates werkt net als 'SELECT DISTINCT'
show_data =  merge_all[['ADDRESS1', 'FIRST_NAME', 'LAST_NAME']].drop_duplicates()
show_data

                            ADDRESS1 FIRST_NAME      LAST_NAME
0      75, rue du Faubourg St-Honoré      Denis           Pagé
1                     Schwabentor 35      Frank          Fuchs
2                   Leopoldstraße 36      Fritz         Hirsch
3                    Piazza Duomo, 1      Maria      Iacobucci
4                Singelgravenplein 4       Kick        Kalkman
5                Isafjordsgatan 30 C      Karin      Bergström
6       7800, 756 - 6th Avenue. S.W.      Sally          White
7                   789 Yonge Street    Georges  Saint-Germain
8             1288 Dorchester Avenue       Alex      Rodriguez
9                    299 Yale Avenue   Samantha          Floyd
10                    10032 NW 186th      Julie          Olsen
11        1288 South Barrington Ave.      Corey         Wright
12               6c, rue de l'Église      Julie        Béchard
13  Prol. Paseo de la Reforma No. 51      Lucía          Reyna
14                  2315 Queen's Ave      Alice         Walter
15             Avenida Paulista, 333     Bayard          Lopes
16                    Victoria House     Walter         Taylor
17                    3 Albany Court      Polly         Linton
18                 Interleuvenlaan 2      Gracy        Gellens

Geef een overzicht met daarin van de verkopers hun functie en indien zij iets hebben verkocht de datum waarop de verkoop heeft plaatsgevonden. Laat alleen de verschillende namen van de posities zien van de verkopers die het woord ‘Manager’ in hun positienaam hebben staan. (2 kolommen, 7 rijen)

In [23]:
staff_query = pd.read_sql_query("SELECT * FROM sales_staff", con)
order_query = pd.read_sql_query("SELECT * FROM order_header", con)

managers = staff_query[staff_query['POSITION_EN'].str.contains('Manager')]

merge_all = pd.merge(managers, order_query, how='inner', on='SALES_BRANCH_CODE')

resultaat = merge_all[['POSITION_EN', 'ORDER_DATE']].drop_duplicates()
resultaat

          POSITION_EN  ORDER_DATE
0      Branch Manager  2022-04-03
1      Branch Manager  2022-07-12
2      Branch Manager  2022-03-18
3      Branch Manager  2022-07-07
4      Branch Manager  2022-04-05
...               ...         ...
5159  General Manager  2022-10-05
5160  General Manager  2022-10-07
5227   Branch Manager  2022-08-13
5246   Branch Manager  2024-07-07
5269   Branch Manager  2024-09-07

[1908 rows x 2 columns]

Geef een overzicht met daarin de verschillende namen van producten en bijbehorende namen van producttypen van de producten waarvoor ooit meer dan 750 stuks tegelijk verkocht zijn. (2 kolommen, 9 rijen)

In [24]:
order_details = pd.read_sql_query("SELECT * FROM order_details", con)
product_query = pd.read_sql_query("SELECT * FROM product", con)
product_type_query = pd.read_sql_query("SELECT * FROM product_type", con)

# Where statement 
grote_order = order_details.loc[order_details['QUANTITY'] > 750]

merge_product = pd.merge(product_query, product_type_query, how='inner', on='PRODUCT_TYPE_CODE')
merge_all = pd.merge(order_details, merge_product, how='inner', on='PRODUCT_NUMBER')

resultaat = merge_all[['PRODUCT_NAME', 'PRODUCT_TYPE_EN']].drop_duplicates()
resultaat

               PRODUCT_NAME PRODUCT_TYPE_EN
0       TrailChef Water Bag    Cooking Gear
9         TrailChef Canteen    Cooking Gear
19    TrailChef Kitchen Kit    Cooking Gear
27            TrailChef Cup    Cooking Gear
35       TrailChef Cook Set    Cooking Gear
...                     ...             ...
1216         Granite Hammer           Tools
1224         Granite Shovel           Tools
1233           Granite Grip           Tools
1244            Granite Axe           Tools
1254        Granite Extreme           Tools

[115 rows x 2 columns]

Geef een overzicht met daarin de productnamen waarvan ooit meer dan 40% korting is verleend. De formule voor korting is: (unit_price - unit_sale_price) / unit_price (1 kolom, 8 rijen)

In [25]:
order_details = pd.read_sql_query("SELECT * FROM order_details", con)
product_query = pd.read_sql_query("SELECT * FROM product", con)

# Ik doe het nu eerst apart
# De discount bestaat niet, dus ik heb dat gemaakt zodat ik de korting erin kan douwen
order_details['DISCOUNT'] = (order_details['UNIT_PRICE'] - order_details['UNIT_SALE_PRICE'] / order_details['UNIT_PRICE'])
grote_korting = order_details[order_details['DISCOUNT'] > 0.40]

merge_all = pd.merge(grote_korting, product_query, on='PRODUCT_NUMBER')
resultaat = merge_all[['PRODUCT_NAME']].drop_duplicates()
resultaat

               PRODUCT_NAME
0       TrailChef Water Bag
9         TrailChef Canteen
19    TrailChef Kitchen Kit
27            TrailChef Cup
35       TrailChef Cook Set
...                     ...
1216         Granite Hammer
1224         Granite Shovel
1233           Granite Grip
1244            Granite Axe
1254        Granite Extreme

[115 rows x 1 columns]

Geef een overzicht met daarin de retourreden van producten waarvan ooit meer dan 90% van de aangeschafte hoeveelheid is teruggebracht (return_quantity/quantity). (1 kolom, 3 rijen)

In [26]:
order_details = pd.read_sql_query("SELECT * FROM order_details", con)
return_reason_query = pd.read_sql_query("SELECT * FROM return_reason", con)
returned_item_query = pd.read_sql_query("SELECT * FROM returned_item", con)

merge_quantity = pd.merge(order_details, returned_item_query, how='inner', on='ORDER_DETAIL_CODE')

# Merge eerst bij elkaar zodat ze bij elkaar horen.
merge_quantity['RETURN_PERCENTAGE'] = (merge_quantity['RETURN_QUANTITY'] / merge_quantity['QUANTITY'])

# Binnen de serie kun je ook de statement toepassen
grote_retour = merge_quantity[merge_quantity['RETURN_PERCENTAGE'] > 0.90]
merge_all = pd.merge(grote_retour, return_reason_query, how='inner', on='RETURN_REASON_CODE')

resultaat = merge_all[['RETURN_DESCRIPTION_EN']].drop_duplicates()
resultaat.head(3)

    RETURN_DESCRIPTION_EN
0   Wrong product ordered
2   Wrong product shipped
3  Unsatisfactory product

## Selecties op meerdere tabellen met functies

Geef een overzicht met daarin per producttype het aantal producten die tot dat producttype behoren. (2 kolommen, 21 rijen)

In [27]:
product_query = pd.read_sql_query("SELECT * FROM product", con)
product_type_query = pd.read_sql_query("SELECT * FROM product_type", con)

merge_all = pd.merge(product_query, product_type_query, how='outer', on='PRODUCT_TYPE_CODE')

resultaat = merge_all.groupby('PRODUCT_TYPE_EN').size().reset_index(name='aantal_producten')
resultaat

         PRODUCT_TYPE_EN  aantal_producten
0             Binoculars                 4
1   Climbing Accessories                 7
2           Cooking Gear                10
3                Eyewear                 5
4              First Aid                 5
5       Golf Accessories                 4
6      Insect Repellents                 5
7                  Irons                 4
8                 Knives                 5
9               Lanterns                12
10            Navigation                 4
11                 Packs                 6
12               Putters                 3
13                  Rope                 4
14                Safety                 4
15         Sleeping Bags                 7
16             Sunscreen                 5
17                 Tents                 6
18                 Tools                 6
19               Watches                 5
20                 Woods                 4

Geef een overzicht met daarin per land het aantal vestigingen van klanten die zich in dat land bevinden. (2 kolommen, 21 rijen)

In [28]:
# Land, aantal_vestigingen
country_query = pd.read_sql_query('SELECT * FROM country', con)
sales_branch = pd.read_sql_query('SELECT * FROM sales_branch', con)

merge_all = pd.merge(country_query, sales_branch, how='inner', on='COUNTRY_CODE')
# .nunique() toont hoeveel waardes binnen de tabel zit.
# print(merge_all.nunique())

# Deze groupby kan ook gewoon een waarde pakt binnen de tabel en size zorgt ervoor dat het opteld.
resultaat = merge_all.groupby('COUNTRY').size().reset_index(name='aantal_vestigingen')
resultaat

           COUNTRY  aantal_vestigingen
0        Australia                   1
1          Austria                   1
2          Belgium                   1
3           Brazil                   1
4           Canada                   2
5            China                   1
6          Finland                   1
7           France                   2
8          Germany                   2
9            Italy                   1
10           Japan                   2
11           Korea                   1
12          Mexico                   1
13     Netherlands                   1
14           Spain                   1
15          Sweden                   1
16     Switzerland                   1
17          Taiwan                   1
18  United Kingdom                   2
19   United States                   4

Geef een overzicht met daarin van de producten behorend tot het producttype ‘Cooking Gear’ per productnaam de totaal verkochte hoeveelheid en de gemiddelde verkoopprijs. Sorteer de uitkomst op totaal verkochte hoeveelheid. (6 kolommen, 10 rijen)

In [29]:
order_details = pd.read_sql_query("SELECT * FROM order_details", con)
product_query = pd.read_sql_query("SELECT * FROM product", con)
product_type_query = pd.read_sql_query("SELECT * FROM product_type", con)

product_all = pd.merge(product_query, product_type_query, how='inner', on='PRODUCT_TYPE_CODE')

cooking_gear = product_all[product_all['PRODUCT_TYPE_EN'] == 'Cooking Gear']

merge_all = pd.merge(cooking_gear, order_details, how='inner', on='PRODUCT_NUMBER')

resultaat = (
    merge_all
    .groupby(['PRODUCT_NUMBER','PRODUCT_NAME','PRODUCT_TYPE_CODE','PRODUCT_TYPE_EN'])
    # agg is average
    .agg(totaal_verkocht=('QUANTITY','sum'),gemiddelde_verkoopprijs=('UNIT_SALE_PRICE','mean')).reset_index()
    # sort_values werkt net als ORDER BY + waar je een naam kunt geven
    .sort_values(by='totaal_verkocht', ascending=False)
)

# head werkt net als de 'TOP' zoals SELECT TOP 10 
resultaat = resultaat.head(10)

resultaat

,PRODUCT_NUMBER,PRODUCT_NAME,PRODUCT_TYPE_CODE,PRODUCT_TYPE_EN,totaal_verkocht,gemiddelde_verkoopprijs
0,1,TrailChef Water Bag,1,Cooking Gear,36738,6.032506
3,4,TrailChef Cup,1,Cooking Gear,27418,6.976490
1,2,TrailChef Canteen,1,Cooking Gear,26544,11.979418
2,3,TrailChef Kitchen Kit,1,Cooking Gear,22206,22.345975
9,10,TrailChef Utensils,1,Cooking Gear,13776,17.294151
7,8,TrailChef Double Flame,1,Cooking Gear,12476,132.672882
4,5,TrailChef Cook Set,1,Cooking Gear,10878,51.687926
8,9,TrailChef Kettle,1,Cooking Gear,8826,12.201235
6,7,TrailChef Single Flame,1,Cooking Gear,8504,63.827622
5,6,TrailChef Deluxe Cook Set,1,Cooking Gear,3110,121.217638

Geef een overzicht met daarin per land de naam van het land, de naam van de stad waar de verkoopafdeling is gevestigd (noem de kolomnaam in het overzicht ‘verkoper’) en het aantal steden waar zich klanten bevinden in dat land (noem de kolomnaam in het overzicht ‘klanten’) (3 kolommen, 29 rijen)

In [30]:
branch_query = pd.read_sql_query("SELECT * FROM sales_branch", con)
country_query = pd.read_sql_query("SELECT * FROM country", con)

# Landnamen toevoegen
merge_all = pd.merge(branch_query, country_query, how='inner', on='COUNTRY_CODE')
merge_all.nunique()

# De verkoper's land
verkopers = merge_all[['COUNTRY', 'CITY']].rename(columns={'CITY': 'verkoper'})
# Hoeveelheid klanten met behulp van .nunique()
klanten = merge_all.groupby('COUNTRY')['CITY'].nunique().reset_index(name='klanten')

# Beide variabele hebben COUNTRY in hun tabel.
resultaat = pd.merge(verkopers, klanten, how='inner', on='COUNTRY')
resultaat

           COUNTRY          verkoper  klanten
0           France             Paris        2
1            Italy            Milano        1
2      Netherlands         Amsterdam        1
3          Germany           Hamburg        2
4          Germany           München        2
5           Sweden             Kista        1
6           Canada           Calgary        2
7           Canada           Toronto        2
8    United States            Boston        4
9    United States           Seattle        4
10   United States       Los Angeles        4
11   United States             Miami        4
12          France              Lyon        2
13          Mexico  Distrito Federal        1
14           Japan             Tokyo        2
15           Japan        Osaka City        2
16       Australia         Melbourne        1
17           Spain            Bilbao        1
18          Brazil         São Paulo        1
19         Finland            Kuopio        1
20           Korea             Seoul        1
21          Taiwan         San Chung        1
22           China          Shanghai        1
23  United Kingdom            London        2
24  United Kingdom        Birmingham        2
25     Switzerland            Zürich        1
26         Belgium          Heverlee        1
27         Austria              Wien        1

## Pythonvertalingen van SUBSELECT en UNION met o.a. for-loops

Geef een overzicht met daarin de voornaam en de achternaam van de medewerkers die nog nooit wat hebben verkocht (2 kolommen, 25 rijen)

In [31]:
staff_query = pd.read_sql_query("SELECT * FROM sales_staff", con)
order_query = pd.read_sql_query("SELECT * FROM order_header", con)

# Alle medewerkers die ooit verkocht hebben
verkopers = order_query['SALES_STAFF_CODE'].unique() #toont alleen getal
# Was even benieuwd wat het verschil is tussen unique en nunique.
print(order_query.nunique())

# Medewerkers die NIET in die lijst zitten
# Zie bron: https://www.geeksforgeeks.org/python/how-to-use-not-in-filter-in-pandas/
# ~ betekend is not.
nooit_verkocht = staff_query[~staff_query['SALES_STAFF_CODE'].isin(verkopers)]

# Alleen gevraagde kolommen
resultaat = nooit_verkocht[['FIRST_NAME', 'LAST_NAME']]

resultaat

ORDER_NUMBER             4784
RETAILER_NAME             109
RETAILER_SITE_CODE        391
RETAILER_CONTACT_CODE     391
SALES_STAFF_CODE           77
SALES_BRANCH_CODE          28
ORDER_DATE                839
ORDER_METHOD_CODE           7
dtype: int64

   FIRST_NAME      LAST_NAME
0       Denis           Pagé
5        Else         Mörike
6       Frank          Fuchs
9       Fritz         Hirsch
10       Jörg          Kunze
12      Maria      Iacobucci
17       Kick        Kalkman
22      Karin      Bergström
25      Sally          White
27      Frank        Bretton
28    Georges  Saint-Germain
33       Alex      Rodriguez
37   Samantha          Floyd
41      Julie          Olsen
45      Corey         Wright
51    Estelle        Johnson
52       Greg        Belding
55      Julie        Béchard
59      Lucía          Reyna
64     Kazumi        Uragome
66      Alice         Walter
84     Walter         Taylor
85   Penelope        Tamrine
88      Polly         Linton
96      Gracy        Gellens

Geef een overzicht met daarin het aantal producten waarvan de marge lager is dan de gemiddelde marge van alle producten samen. Geef in het overzicht tevens aan wat de gemiddelde marge is van dit aantal producten waarvan de marge lager dan de gemiddelde marge van alle producten samen is. (1 kolom, 2 rijen)

In [32]:
product_query = pd.read_sql_query("SELECT * FROM product", con)
order_details_query = pd.read_sql_query("SELECT * FROM order_details", con)

# Marge berekenen (maak gebruik van ander tabel zonder het te mergen :)
product_query['MARGE'] = order_details_query['UNIT_PRICE'] - order_details_query['UNIT_COST']

# Gemiddelde marge van alle producten 
gemiddelde_marge = product_query['MARGE'].mean()

# Producten met marge lager dan het gemiddelde
lagere_marge = product_query[product_query['MARGE'] < gemiddelde_marge]

# Overzicht maken. Moest wel veel dingen vullen binnen Dataframe. Index werkt als een kolom.
# Round zorgt ervoor dat het afgerond is.
resultaat = pd.DataFrame({'waarde': [lagere_marge.shape[0], round(lagere_marge['MARGE'].mean(), 2)]}, 
                         index=['aantal_producten','gemiddelde_marge'])

resultaat

                  waarde
aantal_producten   73.00
gemiddelde_marge    9.45

Geef een overzicht met daarin de namen van de producten die voor meer dan 500 (verkoopprijs) zijn verkocht maar nooit zijn teruggebracht. (1 kolom, 13 rijen)

In [33]:
product_query = pd.read_sql_query("SELECT * FROM product", con)
order_details = pd.read_sql_query("SELECT * FROM order_details", con)
returned_item = pd.read_sql_query("SELECT * FROM returned_item", con)

dure_verkoop = order_details[order_details['UNIT_SALE_PRICE'] > 500]
# Unique toont alle bestaande codes binnen een lijst. Nunique alleen hoeveelheid van elk tabel
teruggebrachte_orders = returned_item['ORDER_DETAIL_CODE'].unique()
# 
niet_teruggebracht = dure_verkoop[dure_verkoop['ORDER_DETAIL_CODE'].isin(teruggebrachte_orders)]

merge_all = pd.merge(niet_teruggebracht, product_query, on='PRODUCT_NUMBER', how='inner')

resultaat = merge_all[['PRODUCT_NAME']].drop_duplicates()

resultaat

                         PRODUCT_NAME
0                           Star Dome
1                        Star Gazer 6
3                        Star Gazer 3
4   Lady Hailstorm Titanium Woods Set
8        Hailstorm Titanium Woods Set
16           Hailstorm Titanium Irons
21         Lady Hailstorm Steel Irons
25                       Star Gazer 2
26      Lady Hailstorm Titanium Irons
36     Lady Hailstorm Steel Woods Set
37              Hailstorm Steel Irons
42                     Husky Rope 200

Geef een overzicht met daarin per (achternaam van) medewerker of hij/zij manager is of niet, door deze informatie toe te voegen als extra 'Ja/Nee'-kolom.<br>
Hint: gebruik een for-loop waarin je o.a. bepaalt of het woord 'Manager' in de functie (position_en) staat. (2 kolommen, 102 rijen).

In [34]:
staff_query = pd.read_sql_query("SELECT * FROM sales_staff", con)

resultaat_lijst = []

# iterrows() zorgt ervoor dat elke rij wordt gesplitst in een indexnummer en een row, waarin alle rijwaarden opgeslagen liggen.
# Ik kan nog beetje herinneren dat bij het veld 'index' dat ik '_' ook kan gebruiken. De '_' betekend dat je het niet hoeft te gebruiken en niet kan gebruiken.
for index, row in staff_query.iterrows():
    if 'Manager' in row['POSITION_EN']:
        manager = 'Ja'
    else:
        manager = 'Nee'
    
    # List toegepast :), append zorgt ervoor dat de waardes toegevoegd wordt.
    # Heb dictionary in een list toegepast
    resultaat_lijst.append({'LAST_NAME': row['LAST_NAME'],'Manager': manager})

# Heb ook Dataframe toegepast
resultaat = pd.DataFrame(resultaat_lijst)

resultaat

     LAST_NAME Manager
0         Pagé      Ja
1       Michel     Nee
2     Clermont     Nee
3       Jauvin     Nee
4    Wiesinger     Nee
..         ...     ...
97    Laermans     Nee
98     De Crée     Nee
99     Lattrez     Nee
100  Seefelder     Nee
101     Grüner     Nee

[102 rows x 2 columns]

Met de onderstaande code laat je Python het huidige jaar uitrekenen.

In [35]:
from datetime import date
date.today().year

2026

Met de onderstaande code selecteer je op een bepaald jaartal uit een datum.

In [36]:
from datetime import datetime

date_str = '16-8-2013'
date_format = '%d-%m-%Y'
date_obj = datetime.strptime(date_str, date_format)

date_obj.year

2013

Geef met behulp van bovenstaande hulpcode een overzicht met daarin op basis van het aantal jaar dat iemand in dienst is of een medewerker ‘kort in dienst’ (minder dan 30 jaar in dienst) of een ‘lang in dienst’ (groter dan gelijk aan 30 jaar in dienst) is. Geef daarbij per medewerker in een aparte kolom zowel ‘kort in dienst’ als ‘lang in dienst’ aan. Gebruik (wederom) een for-loop.<br>
(2 kolommen, 102 rijen)

In [37]:
staff_query = pd.read_sql_query("SELECT * FROM sales_staff", con)

staff_query

# Roept de huidige jaar op
huidige_jaar = date.today().year

resultaat_lijst = []

for _, row in staff_query.iterrows():
    # Datum omzetten naar datetime
    hire_date = datetime.strptime(row['DATE_HIRED'], '%Y-%m-%d')
    
    # Aantal jaren in dienst (trekt van de huidige jaar de hire_date af)
    jaren_in_dienst = huidige_jaar - hire_date.year

    # Classificatie
    if jaren_in_dienst < 30:
        dienstverband = 'kort in dienst'
    else:
        dienstverband = 'lang in dienst'

    resultaat_lijst.append(
        # Dictionary toevoegen in de list.
        {
        'LAST_NAME': row['LAST_NAME'],
        'DIENSTVERBAND': dienstverband
        }
    )

# Schilt weer code te typen.
resultaat = pd.DataFrame(resultaat_lijst)

resultaat

     LAST_NAME   DIENSTVERBAND
0         Pagé  lang in dienst
1       Michel  lang in dienst
2     Clermont  kort in dienst
3       Jauvin  kort in dienst
4    Wiesinger  kort in dienst
..         ...             ...
97    Laermans  kort in dienst
98     De Crée  kort in dienst
99     Lattrez  kort in dienst
100  Seefelder  kort in dienst
101     Grüner  kort in dienst

[102 rows x 2 columns]