# Werkcollege-opdrachten Week 1.1

## Maak een virtual environment

Zorg dat je met behulp van de handleiding *Bouw en gebruik van virtual environments - Handleiding* een virtual environment hebt gemaakt, dat jou en je duopartner garandeert altijd dezelfde versie van geïmporteerde dependencies te gebruiken.<br>
Voeg hier vervolgens de pandas- en de sqlite3-dependency aan toe.<br>
Als je dit allemaal goed hebt gedaan moet de onderstaande code bij jullie allebei succesvol runnen:

In [1]:
import pandas as pd
import sqlite3
import warnings
warnings.simplefilter('ignore')

N.B.: de 2 reeds geschreven coderegels zorgen ervoor dat eventuele warnings, die code-outputs lelijker maken, uitgezet worden.

Zorg er daarnaast voor dat je...
- Het bestand Waarheidstabel.png in dezelfde map als dit notebook hebt staan.
- Het bestand Prinstabel.png in dezelfde map als dit notebook hebt staan.
- Alle informatie onder het kopje *Basisoperaties* van de cheatsheet *Van Java naar Python - Cheatsheet* bij de hand hebt.

## Output, variabelen en input

Geef code waarmee het volgende op het scherm komt te staan:<br>
geef me je geld <br>
of ik gebruik geweld, <br>
toen kwam de controle aangesneld

In [2]:
print("geef me je geld \nof ik gebruik geweld, \ntoen kwam de controle aangesneld")

geef me je geld
of ik gebruik geweld,
toen kwam de controle aangesneld

Declareer 2 variabelen zodat de volgende tekst geprint wordt:<br>
Apenhoofd<br>
Paardenstaart

In [3]:
woord1 = "Apenhoofd"
woord2 = "Paardenstaart"

print(woord1)
print(woord2)

Apenhoofd
Paardenstaart

Voeg code toe zodat het programma het volgende doet:<br>
1): Op het scherm komt A, B, C, D, ..., F, G te staan<br>
2): De gebruiker voert een letter in<br>
3): Op het scherm komt te staan:<br>
Het is inderdaad:<br>
*ingevoerde letter*

In [4]:
print("A, B, C, D, ..., F, G")
alfabet_letter = input("Welke letter mis deze alfabet? Vul in 'A', 'B' of 'Z'.")
alfabet_volgorde = f"A, B, C, D, {alfabet_letter}, F, G"  
print(f"ingevoerde letter: {alfabet_letter}\n")
print(f"resultaat: {alfabet_volgorde}")

A, B, C, D, ..., F, G
ingevoerde letter:

resultaat: A, B, C, D, , F, G

## Stringconcatenatie en Rekenen

Schrijf code dat een inkomen inleest en het volgende uitprint:<br>
Uw inkomen (*ingelezen inkomen*) is zeer acceptabel.

In [5]:
mijn_inkomen = float(input("Hoe groot is je inkomen?"))

if(mijn_inkomen > 10000):
    print(f"Uw inkomen {mijn_inkomen} is zeer onacceptabel😡.")
else:
    print(f"Uw inkomen {mijn_inkomen} is zeer acceptabel😁.")

ValueError: could not convert string to float: ''

De oppervlakte van een driehoek is 1/2 * hoogte * basis<br>
Schrijf code zodat het programma het volgende doet:<br>
1): Op het scherm komt Wat is de basis? te staan<br>
2): De gebruiker voert een basis in<br>
3): Op het scherm komt Wat is de hoogte? te staan<br>
4): De gebruiker voert een hoogte in<br>
5): Op het scherm komt: De oppervlakte van de driehoek is *berekende oppervlakte* te staan

In [ ]:
print("Welkom bij de driehoek berekener :)!!!")

# De basis aan de gebruiker vragen
basis = float(input("Wat is de basis? Vul een nummer in zoals '7.5'"))

# De hoogte aan de gebruiker vragen
hoogte = float(input("Wat is de hoogte? Vul een nummer in zoals '2.5'"))

# De driehoek wordt berekend
driehoek = 0.5 * hoogte * basis

# Resultaat
print(f"De oppervlakte van de driehoek is {driehoek} te staan")

## if() en booleans

Schrijf code dat het volgende doet:<br>
1): De gebruiker voert in hoe oud iemand is<br>
2): De gebruiker voert in of de ouders meegekomen zijn (input is J of N)<br><br>

Als...
- Jonger dan 6, wel ouders: op het scherm staat Je mag het zwembad in
- Jonger dan 6, geen ouders: op het scherm staat Je mag het niet zwembad in
- Leeftijd vanaf 6, geen ouders: op het scherm staat Je mag het zwembad in als je een diploma hebt
- Leeftijd vanaf 6, wel ouders: op het scherm staat Waarom neem je nog je ouders mee?

In [ ]:
age = int(input("Hoe oud ben je?"))
parents_will_come = False
the_value= input("Ga je mee met je ouders? Schrijf 'ja' of 'nee'")

if the_value == "ja":
    parents_will_come = True
else:
    parents_will_come = False

print(parents_will_come)

if age < 6 and parents_will_come == True:
    print("Je mag het zwembad in")
elif age < 6 and parents_will_come == False:
    print("Je mag het niet zwembad in")
elif age >= 6 and parents_will_come == False:
    print("Je mag het zwembad in als je een diploma hebt")
elif age >= 6 and parents_will_come == True:
    print("Waarom neem je nog je ouders mee?")
else:
    print("Geen idee hoe je hier komt😂")

False
Je mag het zwembad in als je een diploma hebt

Schrijf code zodat de boolean-variabelen een en twee aangemaakt worden en waarmee de juiste waarde in de boolean-variabele uitkomst komt te staan. In de waarheidstabel hieronder staat wat de waarde van uitkomst is bij de verschillende mogelijke combinaties van een en twee.<br><br>
<img src="Waarheidstabel.png">

In [ ]:
print("よこそ　bij waarheidstabel")

"""
De waardes
een + twee = uitkomst
waar + waar = waar
waar + onwaar = onwaar
onwaar + waar = waar
onwaar + onwaar = waar
"""
een = bool(input("Kies voor nummer 1: True or False"))
twee = bool(input("Kies voor nummer 2: True or False"))

# Ik moet dan een if else gaan maken.

print(f"1 = {een}, 2 = {twee}")

result_one = een == True and twee == True
result_two = een == True and twee == False
result_three = een == False and twee == True
result_four = een == False and twee == False

if result_one or result_three or result_four:
    print("uitkomst is waar")
else:
    print("uitkomst is niet waar")

よこそ　bij waarheidstabel
1 = True, 2 = True
uitkomst is waar

## Functies

Schrijf een methode wachtwoord die als parameters twee woorden meekrijgt en het volgende controleert:
- Als de woorden gelijk zijn, print het programma gelijk.
- Als de woorden ongelijk zijn print het programma ongelijk.

Vergeet niet dat je de methode niet alleen aan moet maken, maar ook aan moet roepen om output te krijgen.

In [ ]:
# De functie
def woorden_checker(wrd1, wrd2):
    if  wrd1 == wrd2:
        print("gelijk")
    else:
        print("ongelijk")

# De programma
print("Welkom bij de woorden checker!!!")
print("Binnen deze programma wordt er gecontroleerd of de woorden gelijk zijn of niet.")
woord1 = input("Kies je eerste woord")
woord2 = input("Kies je tweede woord")

woorden_checker(woord1, woord2)

Welkom bij de woorden checker!!!
Binnen deze programma wordt er gecontroleerd of de woorden gelijk zijn of niet.
ongelijk

Schrijf de methode zoekPrins die als parameter een prinses meekrijgt en vervolgens de bijbehorende prins oplevert, volgens de volgende tabel:<br><br>
<img src="Prinstabel.png"><br>
Als de naam van de prinses niet in de tabel staat wordt het volgende door de methode teruggegeven: naamloos.<br>
Roep ten slotte de gemaakte methode ook daadwerkelijk aan met een zelfgekozen prinsessennaam.

In [ ]:
def zoekPrins(princess):
    command = princess

    match command:
        case "aurora":
            return "Philip"
        case "ariel":
            return "Eric"
        case "jasmine":
            return "Aladdin"
        case "pocahontas":
            return "John"
        case "belle":
            return "Mr. Beast"
        case "tiana":
            return "Naveen"
        case "mulan":
            return "Shang"
        case _:
            return "haha je prins heeft zelfmoord gepleegd😂"
        
my_little_princess = input("Van welke princess wil je hun prins zoeken?").lower()
print(zoekPrins(my_little_princess))

Mr. Beast

## While-loop

Schrijf de inhoud van de methode wachtwoord. Deze heeft geen parameters en laat de gebruiker twee wachtwoorden invoeren, waarna hij bekijkt of deze gelijk zijn. Zolang dat niet het geval is wordt er eerst Fout, probeer het opnieuw! uitgeprint en moet de gebruiker het opnieuw proberen.<br>Als de gebruiker het goed doet, komt er Succes! op het scherm te staan.

In [ ]:
def password_checker():
    # Eerste check om te controleren of beide wachtwoorden met elkaar 
    wachtwoord = input("Vul uw wachtwoord in")
    herhaal_wachtwoord = input("Herhaal uw wachtwoord")

    #  Als de wachtwoorden niet overeenkomt, dan moet de gebruiker het nog een keer proberen.
    while wachtwoord != herhaal_wachtwoord:
        print("Fout, probeer het opnieuw!")
        wachtwoord = input("Vul uw wachtwoord in")
        herhaal_wachtwoord = input("Herhaal uw wachtwoord")

    print("Succes!")

# Functie oproepen
password_checker()

Succes!

Schrijf de inhoud van de methode tafels. De methode print alle tafels vanaf 1 (dus inclusief de tafel van 1) tot en met de tafel van het meegekregen getal (dus inclusief de tafel van getal).  Zet een witregel tussen alle tafels in. <br>
Let op:
- Gebruik een while-loop
- Gebruik de reeds geschreven methode tafel om een tafel uit te printen

In [ ]:
def tafel(getal: int):
    teller: int = 1

    while(teller <= 10):
        # I guess dit is goed genoeg? Want de \n gebruikt nog een enter oftewel een witregel.
        print(f'{teller} x {getal} = {teller * getal}\n')
        teller += 1

x: int = int(input())
tafel(x)

1 x 1 = 1

2 x 1 = 2

3 x 1 = 3

4 x 1 = 4

5 x 1 = 5

6 x 1 = 6

7 x 1 = 7

8 x 1 = 8

9 x 1 = 9

10 x 1 = 10

## For-loop

Vervang de while-loop door een werkende for-loop. De uitkomst van het programma mag daarbij niet veranderen.

In [ ]:
def loopje():

    aantal = 0

    # De while loop😡
    """ while(aantal <= 10):
            print(f"huidige getal: {aantal}")
            aantal += 1"""
    # De for loop😁 

    # In range zorgt ervoor dat je het getal kunt printen.
    # De range bestaat in 3 delen. De begingetal, eindgetal en overstap. 
    # Eindgetal voorbeeld. Stel je wilt het getal 10, dan moet je het getal '11' invullen. Verwachte eindgetal = eindgetal + 1
    for aantal in range(1, 11):
        print(f"huidige getal: {aantal}")

    # Voor de bewijs, dat het eindgetal meegestuurd wordt.
    print(f"Bewijs dat de 'in range' zo werkt: {aantal}")


loopje()

huidige getal: 1
huidige getal: 2
huidige getal: 3
huidige getal: 4
huidige getal: 5
huidige getal: 6
huidige getal: 7
huidige getal: 8
huidige getal: 9
huidige getal: 10
Bewijs dat de 'in range' zo werkt: 10

Schrijf de methode checkEven die achtereenvolgens 12 getallen inleest en afdrukt hoe vaak het ingevoerde getal even was.

In [ ]:
def checkEven(de_lijst):
    huidige_getal = 0
    even_getal = 0
    # print(f"Huidige getal: {huidige_getal}.\nTest getal: {de_lijst[huidige_getal]}")

    # Ik gebruik de len() zodat hij de lengte van de lijst pakt.
    for huidige_getal in range(0, len(de_lijst)):
        if de_lijst[huidige_getal] % 2 == 0:
            even_getal += 1
            huidige_getal += 1
        else:
            huidige_getal += 1
            # print(huidige_getal)
    
    print(f"Totale even getallen: {even_getal}")

#===== Buiten de functie=====
lijst_met_getallen = []
counter = 1

# Wil hier 12 getallen toevoegen
while len(lijst_met_getallen) != 12:
    getal_toevoegen = int(input(f"Vul {counter} van de 12 in:"))
    lijst_met_getallen.append(getal_toevoegen)
    # print(f"Huidige getal in de lijst: {lijst_met_getallen}")
    counter += 1

# print(lijst_met_getallen[0])
checkEven(lijst_met_getallen)


# """Andere soort opdracht I guess"""
# def checkEven(ingevoerde_getal):
#     huidige_getal = 0
#     even_getal = 0

#     for huidige_getal in range(0, ingevoerde_getal):
#         if huidige_getal % 2 == 0:
#             even_getal += 1
#         huidige_getal += 1
    
#     print(f"Totale even getallen: {even_getal}")

# getal = int(input("Voer een getal in"))
# checkEven(getal)

Totale even getallen: 12

## Objectoriëntatie

Maak een minisysteem voor een kledingwinkel. Maak verschillende klassen voor verschillende soorten kledingstukken, waarbij sommige klassen geërfd worden van andere klassen.
- Maak een klasse Kledingstuk aan, waarin door de constructor een merk, een maat en een prijs geïnitialiseerd worden.
- Maak een klasse Broek en een klasse Shirt, beide erven van de klasse Kledingstuk. Voeg aan Broek een broek_type, en aan Shirt een shirt_type toe (d.m.v. constructorgebruik).
- Maak een klasse Spijkerbroek die erft van broek en een klasse Poloshirt die erft van shirt. Voeg aan Spijkerbroek een blauwtint toe, en aan Poloshirt een kraagsoort (d.m.v. constructorgebruik).
- Implementeer in elke klasse een beschrijvingmethode, waarmee alle informatie over het betreffende kledingstuk wordt afgedrukt.
- Maak van elke klasse een object aan en roep de beschrijvingmethode aan. Controleer nauwkeurig of alles naar behoren werkt.

In [ ]:
class Kledingstuk:
    merk: str
    maat: float
    prijs: float

    def __init__(self, merk: str, maat: float, prijs: float):
        self.merk = merk
        self.maat = maat
        self.prijs = prijs

    def beschrijving(self):
        return(f"Informatie voor een kledingstuk (Parent klasse):\nMerk: {self.merk}\nMaat: {self.maat}\nPrijs: {self.prijs}\n")

# ======Erft van de klasse Kledingstuk ===========
class Broek(Kledingstuk):
    broek_type: str

    def __init__(self, merk: str, maat: float, prijs: float, broek_type: str):
        super().__init__(merk, maat, prijs) 
        self.broek_type = broek_type
    
    def beschrijving(self):
        return(f"Informatie voor een broek (child klasse):\nMerk: {self.merk}\nMaat: {self.maat}\nPrijs: {self.prijs}\nBroek type: {self.broek_type}\n")


class Shirt(Kledingstuk):
    shirt_type: str

    def __init__(self, merk: str, maat: float, prijs: float, shirt_type: str):
        super().__init__(merk, maat, prijs) #Called from the Kledingstuk Class :)
        self.shirt_type = shirt_type

    def beschrijving(self):
        return(f"Informatie voor een broek (child klasse):\nMerk: {self.merk}\nMaat: {self.maat}\nPrijs: {self.prijs}\nShirt type: {self.shirt_type}\n")

# =======Erft een van de klasses Broek en Shirt ============
class Spijkerbroek(Broek):
    blauwetint: str

    def __init__(self, merk: str, maat: float, prijs: float, broek_type: str, blauwetint: str):
        super().__init__(merk, maat, prijs, broek_type)
        self.blauwetint = blauwetint

    def beschrijving(self):
        return(f"Informatie voor een broek (grandchild klasse):\nMerk: {self.merk}\nMaat: {self.maat}\nPrijs: {self.prijs}\nBroek type: {self.broek_type}\nBlauwetint: {self.blauwetint}\n")

class Poloshirt(Shirt):
    kraagsoort: str

    def __init__(self, merk: str, maat: float, prijs: float, shirt_type: str, kraagsoort: str):
        super().__init__(merk, maat, prijs, shirt_type)
        self.kraagsoort = kraagsoort

    def beschrijving(self):
        return(f"Informatie voor een broek (grandchild klasse):\nMerk: {self.merk}\nMaat: {self.maat}\nPrijs: {self.prijs}\nShirt type: {self.shirt_type}\nKraagsoort: {self.kraagsoort}\n")
        

# ============Buiten de klasses ==============

KledingTest1 = Kledingstuk("KledingStuk van 6 7", 67.67, 67.67)
KledingTest2 = Broek("Broek van Minji", 169.00, 16.90, "NewJeans")
KledingTest3 = Shirt("Shirt van Sonic", 67.67, 67.67, "SEGA")
KledingTest4 = Spijkerbroek("Spijkerbroek van Niemand", 100.00, 10.00, "Nintendo", "Ja")
KledingTest5 = Poloshirt("Poloshirt van Polo", 67.67, 67.67, "OldJeans", "Nee")

print(KledingTest1.beschrijving())
print(KledingTest2.beschrijving())
print(KledingTest3.beschrijving())
print(KledingTest4.beschrijving())
# Op ene andere manier is het beetje afgebroken, wel toont het de goede informatie. Geen idee waarom. Komt door de console I guess.
print(KledingTest5.beschrijving())

Informatie voor een kledingstuk (Parent klasse):
Merk: KledingStuk van 6 7
Maat: 67.67
Prijs: 67.67

Informatie voor een broek (child klasse):
Merk: Broek van Minji
Maat: 169.0
Prijs: 16.9
Broek type: NewJeans

Informatie voor een broek (child klasse):
Merk: Shirt van Sonic
Maat: 67.67
Prijs: 67.67
Shirt type: SEGA

Informatie voor een broek (grandchild klasse):
Merk: Spijkerbroek van Niemand
Maat: 100.0
Prijs: 10.0
Broek type: Nintendo
Blauwetint: Ja

Informatie voor een broek (grandchild klasse):
Merk: Poloshirt van Polo
Maat: 67.67
Prijs: 67.67
Shirt type: OldJeans
Kraagsoort: Nee

## Verzamelingen

Kijk nu naar alle info onder het kopje *Verzamelingen* van de cheatsheet *Van Java naar Python - Cheatsheet*.

Initialiseer een lijst met de naam mijn_lijst met de volgende waarden:<br>
Jelle, Marleen, Henk, Fatima, Jelle, Henk

In [ ]:
mijn_lijst = ["Jelle", "Marleen", "Henk", "Fatima", "Jelle", "Henk"]
mijn_lijst

['Jelle', 'Marleen', 'Henk', 'Fatima', 'Jelle', 'Henk']

Probeer nu de eerste waarde uit te lijst te veranderen in een naam naar keuze. Lukt dat?

In [ ]:
mijn_lijst[4] = "Minji"
mijn_lijst

['Jelle', 'Marleen', 'Henk', 'Fatima', 'Minji', 'Henk']

Maak van bovengenoemde lijst nu een tupel, genaamd: mijn_tupel.

In [ ]:
# Tuple and List are similar, but unlike list, tuple is craved in stone and once it is given a value, it can't be changed anymore.
mijn_tuple = ("Jelle", "Marleen", "Henk", "Fatima", "Jelle", "Henk")

Probeer nu de laatste waarde uit te tupel te veranderen in een naam naar keuze. Lukt dat?

In [ ]:
# Nee dit mag niet, omdat de tuple niet van zijn verleden houdt en zijn trauma wilt vermijden.
mijn_tuple[len(mijn_tuple) - 1] = "Hanni"
mijn_tuple

# # Wat wel mag is als je de mijn_tuple leegmaakt en een nieuwe waarde toevoegd.
# mijn_tuple = ()
# mijn_tuple = ("Escanor", "Meliodas", "Ban", "King", "Diane", "Gowther", "Merlin")
# mijn_tuple

TypeError: 'tuple' object does not support item assignment

Initialiseer een dictionary met de volgende key-value-combinaties:
- naam: "Jelle"
- leeftijd: 30
- beroep: "Docent"
- hobby: "Volleybal"

In [ ]:
mijn_dic_met_een_t_erachter = {
    "naam": "Jelle",
    "leeftijd": 30,
    "beroep": "Docent",
    "hobby": "Volleybal",
}

mijn_dic_met_een_t_erachter

{'naam': 'Jelle', 'leeftijd': 30, 'beroep': 'Docent', 'hobby': 'Volleybal'}

Probeer nu de naam te veranderen naar een naam naar keuze. Lukt dat?

In [ ]:
mijn_dic_met_een_t_erachter["naam"] = "Teddiursa"
mijn_dic_met_een_t_erachter

{'naam': 'Teddiursa', 'leeftijd': 30, 'beroep': 'Docent', 'hobby': 'Volleybal'}

## Data klaarzetten

Zet de volgende bestanden in een makkelijk terug te vinden map:
- go_sales.sqlite
- go_crm.sqlite
- go_staff.sqlite

Bestudeer de bovenste 3 bestanden met DB Browser (SQLite) dat <a href="https://sqlitebrowser.org/dl/">hier</a> te downloaden is. Wat valt je op qua datatypen?<br>

## Databasetabel inlezen

Creëer een databaseconnectie met het bestand go_sales.sqlite. Let op: deze staat in de map "data", die op zijn beurt in de hoofdmap staat. Tip: met `"../"` in `connect()` kun je naar de bovenliggende map gaan.

In [ ]:
# Op ene andere manier moet ik eerst de imports gaan runnen.
con = sqlite3.connect('./go_sales.sqlite')
sql_query = "SELECT * FROM country"
# # Testen of dit werkt
data = pd.read_sql_query(sql_query, con)
# data_of_japan = pd.read_sql_query('SELECT * FROM country WHERE COUNTRY = "Japan"', con)

print(data)

    COUNTRY_CODE         COUNTRY LANGUAGE CURRENCY_NAME
0              1          France       EN        francs
1              2         Germany       EN         marks
2              3   United States       EN       dollars
3              4          Canada       EN       dollars
4              5         Austria       EN    schillings
5              6           Italy       EN          lira
6              7     Netherlands       EN      guilders
7              8     Switzerland       EN        francs
8              9  United Kingdom       EN        pounds
9             10          Sweden       EN         krona
10            11           Japan       EN           yen
11            12          Taiwan       EN    new dollar
12            13           Korea       EN           won
13            14           China       EN      renminbi
14            16       Australia       EN       dollars
15            17         Belgium       EN        francs
16            18         Denmark       EN        kroner
17            19           Spain       EN       pesetas
18            20          Mexico       EN         pesos
19            21          Brazil       EN         reals
20            22         Finland       EN        markka

<b>Let goed op:</b><br>
Als je per ongeluk een verkeerde bestandsnaam ingeeft, maakt Python zélf een leeg databasebestand aan! Er ontstaat dan dus een nieuwe .sqlite, en dat is nadrukkelijk <u>niet de bedoeling.</u>

Gebruik de onderstaande sql_query om te achterhalen welke databasetabellen in go_sales zitten.

In [ ]:
# Bekijkt welke tabellen bestaan
sql_query = "SELECT name FROM sqlite_master WHERE type='table';"

#Vul dit codeblok verder in
data = pd.read_sql_query(sql_query, con)

data

             name
0         country
1   order_details
2    order_header
3    order_method
4         product
5    product_line
6    product_type
7   retailer_site
8   return_reason
9   returned_item
10   sales_branch
11    sales_staff

Krijg je lege output? Dan heb je per ongeluk een leeg  databasebestand (.sqlite) aangemaakt.<br>
Lees de informatie onder het kopje <b>Let goed op:</b> hierboven nog eens goed door.

Gebruik de gecreëerde databaseconnectie om de resultaten van de volgende query in een DataFrame te zetten:<br>
*SELECT * FROM sales_staff*

In [ ]:
con = sqlite3.connect('./go_staff.sqlite')

# Gewoon met een pd van panda de select query gebruiken
# Heb deze link gebruikt: https://www.geeksforgeeks.org/pandas/working-with-database-using-pandas/

data = pd.read_sql_query("SELECT * FROM sales_staff", con)

print(data)

     SALES_STAFF_CODE FIRST_NAME  LAST_NAME                   POSITION_EN  \
0                   4      Denis       Pagé                Branch Manager
1                   5  Élizabeth     Michel  Level 3 Sales Representative
2                   6      Émile   Clermont  Level 1 Sales Representative
3                   7    Étienne     Jauvin  Level 2 Sales Representative
4                  12    Elsbeth  Wiesinger  Level 2 Sales Representative
..                ...        ...        ...                           ...
97                120      Giele   Laermans  Level 1 Sales Representative
98                121   François    De Crée  Level 1 Sales Representative
99                122     Yvette    Lattrez  Level 3 Sales Representative
100               123      Willi  Seefelder  Level 2 Sales Representative
101               124     Sabine     Grüner  Level 3 Sales Representative

            WORK_PHONE  EXTENSION                FAX                   EMAIL  \
0    +33 1 68 94 52 20      325.0  +33 1 68 94 56 60       DPage@grtd123.com
1    +33 1 68 94 52 20      336.0  +33 1 68 94 56 60     EMichel@grtd123.com
2    +33 1 68 94 52 20      378.0  +33 1 68 94 56 60   EClermont@grtd123.com
3    +33 1 68 94 52 20      398.0  +33 1 68 94 56 60     EJauvin@grtd123.com
4    +(49) 40 663 1990     1818.0  +(49) 40 663 4571  EWiesinger@grtd123.com
..                 ...        ...                ...                     ...
97     +32 16 20.73.21     1340.0    +32 16 20.73.32   GLaermans@grtd123.com
98     +32 16 20.73.21     1642.0    +32 16 20.73.32     FDecree@grtd123.com
99     +32 16 20.73.21     1633.0    +32 16 20.73.32    YLattrez@grtd123.com
100  +(43) 13 79 56 32      325.0  +(43) 13 79 56 33  WSeefelder@grtd123.com
101  +(43) 13 79 56 32      348.0  +(43) 13 79 56 33     SGruner@grtd123.com

     DATE_HIRED  SALES_BRANCH_CODE  MANAGER_CODE
0    1996-11-03                  6            18
1    1995-06-08                  6             4
2    1998-04-07                  6             4
3    1997-08-16                  6             4
4    1997-02-27                 13            14
..          ...                ...           ...
97   1999-11-15                 38           119
98   1999-12-01                 38           119
99   1999-12-09                 38           119
100  1998-10-28                 39            18
101  1998-02-18                 39            18

[102 rows x 11 columns]

## Datumkolommen afhandelen

Zoals je misschien al hebt gezien in DB Browser, zijn datums als TEXT opgeslagen, en niet als DATE, DATETIME o.i.d. Hier moeten we dus nog even "typische datumkolommen" van maken. Dat doen we met de volgende code:

In [ ]:
sales_staff = sqlite3.connect('./go_staff.sqlite')

# # # Van de opdracht zelf (blijjkbaar mist het een query😅)
# sales_staff['DATE_HIRED'] = pd.to_datetime(sales_staff['DATE_HIRED'])
# sales_staff.dtypes

# # Checked database, the datatype is indeed in TEXT. It is inside th entity sales_staff
data = pd.read_sql_query("SELECT DATE_HIRED FROM sales_staff", con)
data['DATE_HIRED'] = pd.to_datetime(data['DATE_HIRED'])
sales_staff = data

# Deze code checked de dataype. Dit controleerd of het wel goeed is of niet
print(sales_staff.dtypes)
print(sales_staff)

DATE_HIRED    datetime64[us]
dtype: object
    DATE_HIRED
0   1996-11-03
1   1995-06-08
2   1998-04-07
3   1997-08-16
4   1997-02-27
..         ...
97  1999-11-15
98  1999-12-01
99  1999-12-09
100 1998-10-28
101 1998-02-18

[102 rows x 1 columns]

Als we hier het jaar uit willen halen, schrijven we:

In [ ]:
# Omdat hierboven ik de datatype van TEXT -> DATETIME veranderd heb, kan ik het jaar oproepen.
pd.DatetimeIndex(data['DATE_HIRED']).year

Index([1996, 1995, 1998, 1997, 1997, 1999, 1997, 1998, 1996, 1996,
       ...
       1998, 2000, 1999, 2000, 1999, 1999, 1999, 1999, 1998, 1998],
      dtype='int32', name='DATE_HIRED', length=102)

Deze zelfde syntax is te gebruiken voor het extraheren van kwartalen, maanden, weken en dagen. Probeer het maar eens!

## DataFrames uitsplitsen en opbouwen met Series

De volgende 5 kolommen hebben betrekking op de contactdetails van elke medewerker in dit DataFrame:
- SALES_STAFF_CODE
- WORK_PHONE
- EXTENSION
- FAX
- EMAIL

Maak van elk van deze 5 kolommen een serie.

In [ ]:
con = sqlite3.connect('./go_sales.sqlite')

sql_query = "SELECT SALES_STAFF_CODE, WORK_PHONE, EXTENSION, FAX, EMAIL FROM sales_staff"
data = pd.read_sql_query(sql_query, con)

data_ssc = data['SALES_STAFF_CODE']
data_wp = data['WORK_PHONE']
data_ex = data['EXTENSION']
data_f = data['FAX']
data_em = data['EMAIL']

# Check the datatypes
print(type(data)) # dataframe (entiteit; hele tabel)
print(type(data_ssc)) # series (attribuut; een waarde van een tabel)

<class 'pandas.DataFrame'>
<class 'pandas.Series'>

Zet allevijf gecreëerde series als kolommen naast elkaar in een DataFrame (*contact_details*). Gebruik pd.concat(...)<br>
Hulpvraag: welke waarde geef je aan de axis-parameter?

In [ ]:
# deze website gebruikt https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html en https://www.geeksforgeeks.org/pandas/how-to-concatenate-two-or-more-pandas-dataframes/
# Keys moet in strings. Het is gaat van row.
# Axis 0 = verticaal, maar axis 1 horizontaal
contact_details = pd.concat([data_ssc, data_wp, data_ex, data_f, data_em], keys=["Sales Staff Code", "Workphone", "Extension", "Fax", "Email"], axis=1)
print(contact_details)

print(type(contact_details)) #Bewijs dat het een Dataframe geworden is

     Sales Staff Code          Workphone  Extension                Fax  \
0                   4  +33 1 68 94 52 20      325.0  +33 1 68 94 56 60
1                   5  +33 1 68 94 52 20      336.0  +33 1 68 94 56 60
2                   6  +33 1 68 94 52 20      378.0  +33 1 68 94 56 60
3                   7  +33 1 68 94 52 20      398.0  +33 1 68 94 56 60
4                  12  +(49) 40 663 1990     1818.0  +(49) 40 663 4571
..                ...                ...        ...                ...
97                120    +32 16 20.73.21     1340.0    +32 16 20.73.32
98                121    +32 16 20.73.21     1642.0    +32 16 20.73.32
99                122    +32 16 20.73.21     1633.0    +32 16 20.73.32
100               123  +(43) 13 79 56 32      325.0  +(43) 13 79 56 33
101               124  +(43) 13 79 56 32      348.0  +(43) 13 79 56 33

                      Email
0         DPage@grtd123.com
1       EMichel@grtd123.com
2     EClermont@grtd123.com
3       EJauvin@grtd123.com
4    EWiesinger@grtd123.com
..                      ...
97    GLaermans@grtd123.com
98      FDecree@grtd123.com
99     YLattrez@grtd123.com
100  WSeefelder@grtd123.com
101     SGruner@grtd123.com

[102 rows x 5 columns]
<class 'pandas.DataFrame'>

## Series en DataFrames maken vanuit lists en dictionaries

Met .head(*getal*) kan je de bovenste *getal* rijen van een tabel selecteren.<br>
Selecteer op deze manier de bovenste 5 rijen van *contact_details*.<br>
Sla dit resultaat op in een nieuw DataFrame.

In [ ]:
# Run de bovenste code regel eerst :)
contact_details_top_5 =contact_details.head(5)

print(contact_details_top_5)

   Sales Staff Code          Workphone  Extension                Fax  \
0                 4  +33 1 68 94 52 20      325.0  +33 1 68 94 56 60
1                 5  +33 1 68 94 52 20      336.0  +33 1 68 94 56 60
2                 6  +33 1 68 94 52 20      378.0  +33 1 68 94 56 60
3                 7  +33 1 68 94 52 20      398.0  +33 1 68 94 56 60
4                12  +(49) 40 663 1990     1818.0  +(49) 40 663 4571

                    Email
0       DPage@grtd123.com
1     EMichel@grtd123.com
2   EClermont@grtd123.com
3     EJauvin@grtd123.com
4  EWiesinger@grtd123.com

Aan deze 10 rijen met contactdetails willen we 3 kolommen toevoegen: 'FIRST_LANGUAGE', 'SECOND_LANGUAGE' & 'THIRD_LANGUAGE'.<br>
Iedereens 'First Language' is Engels, afgekort 'EN'. Maak een lijst waarin 5x 'EN' staat.<br>
Converteer deze lijst vervolgens naar een serie en voeg deze horizontaal samen met het resultaat van de vorige opdracht.<br>
Vergeet niet een passende naam te geven aan de nieuw ontstane kolom.

In [ ]:
language_list = ['EN', 'EN', 'EN', 'EN', 'EN']
data = pd.Series(language_list)
# print(data)

# Maak een data voor de dataframe
df = pd.DataFrame(language_list,
                  columns = ['FIRST_LANGUAGE'])
# print(df)

# Ga deze data toevoegen aan de contact details
# The `print(df)` statement is printing the DataFrame `df` to the console. This will display the contents of the DataFrame `df`, showing the data in a tabular format with rows and columns.
contact_details_top_5['FIRST_LANGUAGE'] = df['FIRST_LANGUAGE']
contact_details_fl = contact_details_top_5
contact_details_fl

,Sales Staff Code,Workphone,Extension,Fax,Email,FIRST_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN

Maak nu de tweede kolom ('SECOND_LANGUAGE'). Maak daarvoor een dictionary, met daarin...
- Als keys: alle indexen uit het resultaat van het vorige codeblok.
- Als values: bij de eerste 3 elementen 'FR' (Frankrijk), bij de laatste 2 'DE' (Duitsland).

Maak vervolgens ook hier weer een serie van en voeg ook deze weer horizontaal samen met het rsultaat van de vorige opdracht.<br>
Vergeet niet een passende naam te geven aan de nieuw ontstane kolom.

In [ ]:
the_list = ['FR', 'FR', 'FR', 'DE', 'DE']
list_2 =  pd.Series(the_list)

print(list_2)

second_language = {
    'SECOND_LANGUAGE': list_2
}

# Bij een dictionary hoef je geen lijst en kolom mee te geven omdat het al gedaan is
df_2 = pd.DataFrame(second_language)

contact_details_fl['SECOND_LANGUAGE'] = df_2['SECOND_LANGUAGE']
contact_details_sl = contact_details_fl
contact_details_sl

0    FR
1    FR
2    FR
3    DE
4    DE
dtype: str

,Sales Staff Code,Workphone,Extension,Fax,Email,FIRST_LANGUAGE,SECOND_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN,FR
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN,FR
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN,FR
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN,DE
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN,DE

Maak ten slotte de derde kolom ('THIRD_LANGUAGE') door een dictionary te maken met daarin...
- Als key: de naam van de nieuwe kolom. Zie je het verschil qua keys met de vorige opdracht?
- Als waarde: een lijst met daarin 'NL', 'NL', 'JPN', 'JPN', 'KOR'.

Converteer deze dictionary nu naar een DataFrame en voeg deze horizontaal samen met het resultaat van de vorige opdracht.<br>
Waarom hoef je hierna de nieuw ontstane kolom geen passende naam meer te geven?

In [ ]:
the_list_2 = ['NL', 'NL', 'JPN', 'JPN', 'KOR']
third_language = {
    'THIRD_LANGUAGE': the_list_2
}

df_3 = pd.DataFrame(third_language)

contact_details_sl['THIRD_LANGUAGE'] = df_3['THIRD_LANGUAGE']
contact_details_tl = contact_details_sl
contact_details_tl

  THIRD_LANGUAGE
0             NL
1             NL
2            JPN
3            JPN
4            KOR

,Sales Staff Code,Workphone,Extension,Fax,Email,FIRST_LANGUAGE,SECOND_LANGUAGE,THIRD_LANGUAGE
0,4,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,EN,FR,NL
1,5,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,EN,FR,NL
2,6,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,EN,FR,JPN
3,7,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,EN,DE,JPN
4,12,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,EN,DE,KOR

## Data toevoegen

### Rijen

Gebruik de originele databasetabel *sales_staff*.<br>
Voeg een extra rij toe met eigen invulling. Zorg ervoor dat de index netjes doorloopt.<br>
Hulpvraag: welke waarde geef je nu aan axis?

In [ ]:
con = sqlite3.Connection('./go_sales.sqlite')

data = pd.read_sql_query("SELECT * FROM sales_staff", con)

# Een nieuwe dictionary met de data wordt gemaakt.
new_row = {
    'SALES_STAFF_CODE': ['125', '126'],
    'FIRST_NAME': ['Kim Minji', 'Hanni Pham'],
    'LAST_NAME': ['Boss Bunny', 'Co-Bunny'],
    'POSITION_EN': ['Rapper', 'Singer'],
    'WORK_PHONE': ['+82 6 12345678', '+82 6 12345679'],
    'EXTENSION': ['067.0', '068.0'],
    'FAX': ['+82 6 12345678', '82 6 12345679'],
    'EMAIL': ['kimminji@example.com', 'hanni@example.com'],
    'DATE_HIRED': ['2022-07-07', '2022-07-07'],
    'SALES_BRANCH_CODE': ['6', '7'],
}

# Omdat het een dictionary is, kun je het gelijk de concat toepassen.
result = pd.concat([data, pd.DataFrame(new_row)])

result

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13
...,...,...,...,...,...,...,...,...,...,...
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com,1999-12-09,38
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,1998-10-28,39
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39
0,125,Kim Minji,Boss Bunny,Rapper,+82 6 12345678,067.0,+82 6 12345678,kimminji@example.com,2022-07-07,6
1,126,Hanni Pham,Co-Bunny,Singer,+82 6 12345679,068.0,82 6 12345679,hanni@example.com,2022-07-07,7

### Kolommen

Voeg een kolom *FULL_NAME* toe die de waarden van *FIRST_NAME* en *LAST_NAME* achter elkaar zet, gescheiden door een spatie.

In [ ]:
data_full_name = pd.read_sql_query("SELECT FIRST_NAME, LAST_NAME FROM sales_staff", con)
data_full_name

# Maak eerst een serie van de voor en achternaam. Ik heb de dingen gesplitst
full_name = data_full_name['FIRST_NAME'] + " " + data_full_name['LAST_NAME']

data['FULL_NAME'] = full_name

data.head(5)

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE,FULL_NAME
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6,Denis Pagé
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6,Élizabeth Michel
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6,Émile Clermont
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6,Étienne Jauvin
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13,Elsbeth Wiesinger

## Data wijzigen

### Datatypen

Door het attribuut .dtypes van een DataFrame op te vragen krijg je een serie die per kolom het datatype weergeeft. Doe dit bij de originele databasetabel *sales_staff*

In [ ]:
con = sqlite3.Connection('./go_sales.sqlite')

sales_staff = pd.read_sql_query("SELECT * FROM sales_staff", con)
sales_staff

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,336.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,398.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13
...,...,...,...,...,...,...,...,...,...,...
97,120,Giele,Laermans,Level 1 Sales Representative,+32 16 20.73.21,1340.0,+32 16 20.73.32,GLaermans@grtd123.com,1999-11-15,38
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1642.0,+32 16 20.73.32,FDecree@grtd123.com,1999-12-01,38
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1633.0,+32 16 20.73.32,YLattrez@grtd123.com,1999-12-09,38
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,325.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,1998-10-28,39
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39

Hier valt op dat elke kolom het datatype 'object' heeft: Python leest dus alles als string. Wiskundige operaties zijn hierdoor niet mogelijk.<br>
We kunnen proberen om kolommen met getallen, bijvoorbeeld de 'extension', te converteren naar een int. Zie onderstaande code.

In [ ]:
sales_staff['EXTENSION'] = sales_staff['EXTENSION'].astype(int)
sales_staff.dtypes

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

Dit lukt echter niet, omdat er in de kolom 'EXTENSION' lege waarden zitten die niet geconverteerd kunnen worden naar een int.<br>
Wél kan je deze naar een float converteren, zie onderstaande code:

In [ ]:
sales_staff['EXTENSION'] = sales_staff['EXTENSION'].astype(float)
sales_staff.dtypes

SALES_STAFF_CODE       int64
FIRST_NAME               str
LAST_NAME                str
POSITION_EN              str
WORK_PHONE               str
EXTENSION            float64
FAX                      str
EMAIL                    str
DATE_HIRED               str
SALES_BRANCH_CODE      int64
dtype: object

Als we in de rij van 'EXTENSION' kijken zien we dat de conversie van het datatype nu is gelukt.<br>
Dit is <b>randvoorwaardelijk</b> voor het uitvoeren van wiskundige operaties.<br>

### Rijen

Zorg er nu voor dat bij alle extensions 1 wordt opgeteld.

In [ ]:
sales_staff['EXTENSION'] = sales_staff['EXTENSION'] + 1
sales_staff

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION_EN,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
0,4,Denis,Pagé,Branch Manager,+33 1 68 94 52 20,375.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6
1,5,Élizabeth,Michel,Level 3 Sales Representative,+33 1 68 94 52 20,386.0,+33 1 68 94 56 60,EMichel@grtd123.com,1995-06-08,6
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,428.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6
3,7,Étienne,Jauvin,Level 2 Sales Representative,+33 1 68 94 52 20,448.0,+33 1 68 94 56 60,EJauvin@grtd123.com,1997-08-16,6
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1868.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13
...,...,...,...,...,...,...,...,...,...,...
97,120,Giele,Laermans,Level 1 Sales Representative,+32 16 20.73.21,1390.0,+32 16 20.73.32,GLaermans@grtd123.com,1999-11-15,38
98,121,François,De Crée,Level 1 Sales Representative,+32 16 20.73.21,1692.0,+32 16 20.73.32,FDecree@grtd123.com,1999-12-01,38
99,122,Yvette,Lattrez,Level 3 Sales Representative,+32 16 20.73.21,1683.0,+32 16 20.73.32,YLattrez@grtd123.com,1999-12-09,38
100,123,Willi,Seefelder,Level 2 Sales Representative,+(43) 13 79 56 32,375.0,+(43) 13 79 56 33,WSeefelder@grtd123.com,1998-10-28,39
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,398.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39

Elke 'Branch Manager' wordt nu 'General Manager'. Schrijf code zodat deze wijziging doorgevoerd wordt in het DataFrame.

In [ ]:
sales_staff = pd.read_sql_query("SELECT * FROM sales_staff", con)
sales_staff['POSITION_EN'] = sales_staff['POSITION_EN'].replace(to_replace='Branch Manager', value='General Manager')

# Deze code gebruik ik om alle general manager te checken.
print(sales_staff[sales_staff['POSITION_EN'] == "General Manager"])

    SALES_STAFF_CODE FIRST_NAME      LAST_NAME      POSITION_EN  \
0                  4      Denis           Pagé  General Manager
6                 14      Frank          Fuchs  General Manager
9                 17      Fritz         Hirsch  General Manager
12                20      Maria      Iacobucci  General Manager
17                25       Kick        Kalkman  General Manager
22                30      Karin      Bergström  General Manager
25                45      Sally          White  General Manager
28                48    Georges  Saint-Germain  General Manager
33                53       Alex      Rodriguez  General Manager
37                57   Samantha          Floyd  General Manager
41                61      Julie          Olsen  General Manager
45                65      Corey         Wright  General Manager
55                75      Julie        Béchard  General Manager
59                79      Lucía          Reyna  General Manager
66                89      Alice         Walter  General Manager
73                96     Bayard          Lopes  General Manager
84               107     Walter         Taylor  General Manager
85               108   Penelope        Tamrine  General Manager
88               111      Polly         Linton  General Manager
96               119      Gracy        Gellens  General Manager

             WORK_PHONE  EXTENSION                  FAX  \
0     +33 1 68 94 52 20      325.0    +33 1 68 94 56 60
6     +(49) 40 663 1990     1847.0    +(49) 40 663 4571
9     +(49) 89 882 3456      225.0    +(49) 89 882 3455
12   +(39) 02 41 05 400        NaN   +(39) 02 41 20 549
17  +31 (0)20 692 93 94      197.0  +31 (0)20 692 93 06
22     +(46) 08 753 116      215.0     +(46) 08 752 592
25     1 (403) 232-5986      317.0     1 (403) 232-5831
28     1 (416) 493-5595     1245.0     1 (416) 496-9667
33     1 (617) 268-6754     1334.0     1 (617) 268-3464
37     1 (206) 292-0012      331.0     1 (206) 292-3312
41     1 (310) 281-5722     2045.0     1 (310) 281-9087
45     1 (305) 557-4810     3490.0     1 (305) 557-7650
55    +33 4 52 26 33 88     1315.0    +33 4 66 35 98 95
59      +(525) 549 6090      452.0       +(52) 549 6088
66  +(61) 03 2982  4242     1845.0  +(61) 03 2982  4243
73    +55 (11) 344-4444     3490.0    +55 (11) 333-2223
84    +(44) 181 2033144     3547.0    +(44) 181 5030282
85    +(44) 181 2033144     3542.0    +(44) 181 5030282
88    +(44) 121 3505267     1216.0    +(44) 121 3583843
96      +32 16 20.73.21     1349.0      +32 16 20.73.32

                        EMAIL  DATE_HIRED  SALES_BRANCH_CODE
0           DPage@grtd123.com  1996-11-03                  6
6          FFuchs@grtd123.com  1997-01-12                 13
9         FHirsch@grtd123.com  1996-09-12                 14
12     MIacobucci@grtd123.com  1996-08-18                  7
17       KKalkman@grtd123.com  1995-09-06                  9
22     KBergstrom@grtd123.com  1998-04-27                 15
25         SWhite@grtd123.com  1992-03-26                 17
28  GSaintgermain@grtd123.com  1991-10-27                 18
33     ARodriguez@grtd123.com  1992-02-07                 19
37         SFloyd@grtd123.com  1995-07-17                 20
41         JOlsen@grtd123.com  1998-02-18                 22
45        CWright@grtd123.com  1995-10-11                 21
55       JBechard@grtd123.com  1994-09-03                 23
59         LReyna@grtd123.com  1997-03-10                 24
66        AWalter@grtd123.com  1999-09-08                 28
73         BLopes@grtd123.com  1997-08-12                 30
84        WTaylor@grtd123.com  1995-06-09                 35
85       PTamrine@grtd123.com  1998-12-18                 35
88        PLinton@grtd123.com  1996-06-18                 36
96       GGellens@grtd123.com  1999-09-10                 38

### Kolommen

Verander de kolomnaam 'POSITION_EN' naar 'POSITION'.

In [ ]:
# Is blijkbaar een dictionary
sales_staff = sales_staff.rename(columns={'POSITION_EN': 'POSITION'})
sales_staff

,SALES_STAFF_CODE,FIRST_NAME,LAST_NAME,POSITION,WORK_PHONE,EXTENSION,FAX,EMAIL,DATE_HIRED,SALES_BRANCH_CODE
0,4,Denis,Pagé,General Manager,+33 1 68 94 52 20,325.0,+33 1 68 94 56 60,DPage@grtd123.com,1996-11-03,6
2,6,Émile,Clermont,Level 1 Sales Representative,+33 1 68 94 52 20,378.0,+33 1 68 94 56 60,EClermont@grtd123.com,1998-04-07,6
4,12,Elsbeth,Wiesinger,Level 2 Sales Representative,+(49) 40 663 1990,1818.0,+(49) 40 663 4571,EWiesinger@grtd123.com,1997-02-27,13
5,13,Else,Mörike,Regional Manager,+(49) 40 663 1990,1865.0,+(49) 40 663 4571,EMorike@grtd123.com,1999-06-02,13
6,14,Frank,Fuchs,General Manager,+(49) 40 663 1990,1847.0,+(49) 40 663 4571,FFuchs@grtd123.com,1997-01-12,13
...,...,...,...,...,...,...,...,...,...,...
94,117,Frank,Jever,Level 3 Sales Representative,+(41) 17 12 13 14,1154.0,+(41) 17 12 13 20,FJever@grtd123.com,1999-10-18,37
95,118,Gianni,Vertemati,Level 1 Sales Representative,+(41) 17 12 13 14,1254.0,+(41) 17 12 13 20,GVertemati@grtd123.com,2000-02-10,37
96,119,Gracy,Gellens,General Manager,+32 16 20.73.21,1349.0,+32 16 20.73.32,GGellens@grtd123.com,1999-09-10,38
97,120,Giele,Laermans,Level 1 Sales Representative,+32 16 20.73.21,1340.0,+32 16 20.73.32,GLaermans@grtd123.com,1999-11-15,38
101,124,Sabine,Grüner,Level 3 Sales Representative,+(43) 13 79 56 32,348.0,+(43) 13 79 56 33,SGruner@grtd123.com,1998-02-18,39

## Data verwijderen

### Rijen

De medewerkers op indexen 98, 99 en 100 hebben helaas ontslag genomen.<br>
Verwijder de bijbehorende rijen uit het DataFrame. Gebruik slechts één keer de .drop()-methode.

In [ ]:
sales_staff= sales_staff.drop([98, 99, 100])
sales_staff

KeyError: '[98, 99, 100] not found in axis'

### Kolommen

Faxen zijn inmiddels ouderwets: niemand gebruikt zijn/haar faxnummer nog.<br>
Verwijder de bijbehorende kolom uit het DataFrame.

In [ ]:
sales_staff = sales_staff.drop('FAX', axis=1)
sales_staff

KeyError: "['FAX'] not found in axis"